
var Solutions100 = [ [ "uncurated", "imperiled", "verticals", "illegibly",
							  "nymph", "usher", "adapt", "ember", "stave", "elect", "sonic", "steel",
							  "lymph", "ether", "album", "three", "issue", "leave", "sushi", "niece"  ],
							[ "parentage", "televised", "unimpeded", "hamburger",
							  "alter", "earth", "tract", "grits", "sworn", "steam", "raise", "blare",
							  "aster", "berth", "aside", "taste", "roses", "evoke", "rabbi", "orate"  ],
							[ "imagineer", "joyriders", "jackknife", "hamstring",
							  "mouse", "gassy", "night", "exact", "santa", "track", "mason", "sniff",
							  "abuts", "seedy", "guano", "tutor", "reset", "ninja", "mused", "skier"  ],
							[ "teahouses", "immersion", "fantasist", "vaccinate",
							  "extra", "hardy", "units", "elite", "umbra", "sweat", "times", "mucus",
							  "aster", "crazy", "idiom", "suede", "nouns", "table", "tomes", "macho"  ],
							[ "fifteenth", "knowingly", "neopagans", "casserole",
							  "ideal", "titan", "earns", "taper", "dense", "snoop", "being", "sheen",
							  "agent", "salon", "ripen", "screw", "rides", "lingo", "basin", "ideal"  ],
							[ "feathered", "telethons", "telecasts", "wasteless",
							  "etude", "teens", "eight", "elude", "route", "cease", "balsa", "ought",
							  "abuse", "tiers", "gauge", "theme", "lyric", "sauna", "booth", "login"  ],
							[ "implicate", "parameter", "jestingly", "randomise",
							  "media", "loose", "crumb", "total", "truce", "onset", "elfin", "angel",
							  "audio", "drape", "ultra", "balsa", "metro", "shuns", "evade", "fugue"  ],
							[ "yearbooks", "terrified", "nailbrush", "occipital",
							  "equal", "reply", "oiled", "kaput", "pasta", "total", "sonar", "incas",
							  "clump", "inlay", "lapse", "deter", "input", "asset", "stiff", "niche"  ],
							[ "maximized", "beanstalk", "caregiver", "whirlpool",
							  "amity", "inure", "inept", "eight", "opera", "state", "sushi", "erode",
							  "haiku", "rhyme", "eagle", "titan", "pools", "omega", "spent", "spoil"  ],
							[ "glimpsing", "casserole", "westbound", "canvassed",
							  "leapt", "metro", "slept", "noone", "ozone", "erect", "curio", "riven",
							  "await", "vitro", "ebola", "tiers", "score", "elope", "carer", "rival"  ],	//110
							[ "gesturing", "vendettas", "barbecued", "pantheist",
							  "etude", "theft", "raspy", "nurse", "viola", "shrub", "topic", "large",
							  "amuse", "theft", "serve", "yield", "eaves", "scour", "tolet", "parka"  ],
							[ "immersion", "whispered", "wineskins", "vaultlike",
							  "moose", "eagle", "strip", "ovate", "swami", "shave", "clink", "bison",
							  "among", "liege", "reach", "press", "loses", "koala", "cable", "issue"  ],
							[ "filmmaker", "faithfuls", "important", "affirming",
							  "inert", "model", "angle", "erase", "storm", "disco", "ambit", "organ",
							  "field", "intel", "guava", "elect", "mused", "nooks", "aloof", "bagel"  ],
							[ "backdated", "vampirism", "voicemail", "falsettos",
							  "alone", "knead", "armor", "endup", "lotto", "panic", "steam", "alibi",
							  "anode", "sherd", "media", "ripup", "tulip", "often", "stair", "exits"  ],
							[ "zeppelins", "adulation", "sallowest", "quietened",
							  "equip", "puppy", "later", "nanny", "viola", "steal", "shrew", "lairs",
							  "usurp", "empty", "tuned", "royal", "elves", "erode", "split", "rhino"  ],
							[ "nightgown", "beanstalk", "ecologist", "screening",
							  "inept", "hiker", "grave", "whiff", "manic", "drawl", "being", "dregs",
							  "clerk", "enter", "arise", "elfin", "named", "ninja", "bidet", "ideal"  ],
							[ "captivity", "garrotted", "terahertz", "telegraph",
							  "alter", "taper", "valve", "tired", "peace", "drama", "spate", "about",
							  "eatup", "error", "larva", "elder", "roped", "plaza", "smart", "atone"  ],
							[ "factotums", "recharges", "meanwhile", "waitlists",
							  "adder", "tinny", "throb", "magma", "leave", "organ", "teeth", "moral",
							  "addon", "tardy", "rogue", "brash", "igloo", "twang", "timer", "eyrie"  ],
							[ "abundance", "knockoffs", "additions", "daughters",
							  "briar", "naive", "amble", "coach", "typed", "ennui", "sushi", "learn",
							  "alibi", "gorse", "brain", "ethic", "tithe", "ripen", "salvo", "scarf"  ],
							[ "greatness", "garrisons", "backaches", "granaries",
							  "radar", "alone", "notch", "slack", "drama", "butch", "optic", "slave",
							  "rodeo", "nerve", "tiara", "hiker", "redub", "enact", "oasis", "train"  ],	//120
							[ "wearisome", "terrorise", "ballparks", "carpooler",
							  "email", "ratty", "shade", "mount", "santa", "swill", "media", "kiosk",
							  "adapt", "palsy", "azure", "enter", "oasis", "ennui", "maker", "dross"  ],
							[ "raindrops", "addendums", "schooners", "scarecrow",
							  "attic", "nappy", "roses", "polio", "basic", "ditto", "mason", "spear",
							  "cutup", "rocky", "salad", "stole", "cubed", "onset", "mused", "steam"  ],
							[ "granaries", "technopop", "vanishing", "lactating",
							  "rebel", "nurse", "risks", "enema", "ebola", "sushi", "mulch", "mason",
							  "amber", "tilde", "sieve", "stash", "tiers", "nooks", "mambo", "lasso"  ],
							[ "parochial", "parameter", "viscosity", "headlands",
							  "argon", "overt", "heath", "abode", "alibi", "tunic", "watts", "onset",
							  "eagle", "donut", "aloha", "hyena", "await", "deign", "wrote", "taste"  ],
							[ "beanpoles", "larkspurs", "kinematic", "patrician",
							  "eagle", "nutty", "ought", "evade", "alibi", "trove", "samba", "ennui",
							  "argot", "reedy", "guava", "tweak", "craft", "amino", "steep", "manor"  ],
							[ "vacancies", "abilities", "cellblock", "ballerina",
							  "anger", "acrid", "cater", "equip", "shore", "nasal", "until", "lilac",
							  "augur", "lurid", "thumb", "repel", "resin", "nooks", "unlit", "tilde"  ],
							[ "paralyzed", "headgears", "heartless", "candlelit",
							  "aroma", "avail", "yeast", "edict", "shade", "later", "easel", "gross",
							  "aloha", "drawl", "aside", "toted", "easel", "inapt", "eagle", "scour"  ],
							[ "gangplank", "pastorals", "vindicate", "operating",
							  "anvil", "giddy", "limbo", "night", "ennui", "stand", "attic", "trout",
							  "paved", "relay", "magma", "octet", "teens", "ninja", "actor", "troll"  ],
							[ "vilifying", "federated", "vaporizer", "telegraph",
							  "inter", "image", "yearn", "noose", "drama", "rodeo", "sushi", "leave",
							  "extra", "eyrie", "abode", "niece", "rider", "plaid", "salsa", "shade"  ],
							[ "fingertip", "gamecasts", "laundress", "victimise",
							  "issue", "gated", "recap", "incas", "tiara", "human", "eager", "evens",
							  "inset", "tweed", "cocoa", "paste", "match", "spasm", "enema", "greet"  ],		//130
							[ "undressed", "larrikins", "realising", "paramedic",
							  "night", "rangy", "shaft", "elect", "shine", "excel", "blogs", "eaten",
							  "argon", "artsy", "arena", "tutor", "ensue", "iliac", "bleak", "often"  ],
							[ "lecturers", "vegetable", "temperate", "cataracts",
							  "elite", "tried", "rabid", "rodeo", "amaze", "scamp", "aster", "roast",
							  "alibi", "amend", "badge", "drone", "amass", "tiara", "aorta", "trail"  ],
							[ "fervently", "newscasts", "parasails", "lavishing",
							  "ethos", "verge", "niece", "laser", "dogma", "extra", "china", "creel",
							  "abhor", "issue", "ensue", "earls", "hedge", "night", "cocoa", "inert"  ],
							[ "declaring", "idealizes", "hellholes", "lassitude",
							  "exile", "login", "ripup", "novel", "brine", "yokel", "ratio", "dense",
							  "axing", "stern", "paved", "polka", "tubby", "drink", "radii", "tense"  ],
							[ "lightened", "refracted", "megabytes", "embellish",
							  "idler", "hence", "elide", "exult", "graze", "comma", "ovary", "twice",
							  "melon", "eyrie", "inure", "enter", "logic", "spasm", "optic", "agile"  ],
							[ "pacemaker", "sappiness", "nightfall", "labelling",
							  "apace", "every", "atone", "elect", "alibi", "teeth", "aloof", "octal",
							  "awake", "elegy", "omega", "eatup", "leant", "naive", "adorn", "oaths"  ],
							[ "megahertz", "uncharted", "wainscots", "fecundity",
							  "equal", "adept", "epoch", "twist", "salsa", "ocean", "cynic", "aloft",
							  "exude", "unlit", "onion", "hatch", "disco", "tilde", "chair", "noose"  ],
							[ "magnetite", "matriarch", "decreases", "neutrally",
							  "apace", "niece", "toads", "tweet", "knave", "wiser", "delta", "gorge",
							  "erase", "these", "arena", "satyr", "askew", "loads", "dogma", "lyric"  ],
							[ "federally", "thighbone", "withstood", "teleports",
							  "exile", "entry", "aches", "llama", "swami", "teach", "roost", "ditto",
							  "evict", "enemy", "heath", "slang", "onset", "tiara", "redub", "often"  ],
							[ "scoreless", "unclothed", "delighted", "banefully",
							  "chest", "rider", "lease", "snaps", "gable", "sushi", "blush", "grate",
							  "ahead", "enter", "again", "easel", "urges", "lobes", "beget", "usage"  ],		//140
							[ "backdraft", "temptress", "certified", "eagerness",
							  "anode", "kinky", "raves", "feint", "cease", "exert", "shelf", "agape",
							  "adorn", "enemy", "voice", "setup", "niche", "spate", "stair", "exams"  ],
							[ "wearables", "nanometer", "teachings", "facecloth",
							  "epoch", "relic", "baker", "erred", "bathe", "sonic", "khaki", "among",
							  "atoll", "ethic", "karma", "radio", "lobes", "titan", "knave", "awoke"  ],
							[ "echinacea", "thirsting", "magnified", "harmonist",
							  "codes", "inter", "argot", "evade", "circa", "satin", "bluff", "raise",
							  "audit", "miser", "gnash", "their", "nicks", "strut", "burnt", "union"  ],
							[ "madhouses", "pentagons", "harshness", "mandrakes",
							  "angst", "holly", "unlit", "elude", "guava", "evens", "wrong", "floss",
							  "angel", "dotty", "louse", "tweet", "algae", "erase", "oboes", "known"  ],
							[ "endoscopy", "embroiled", "groceries", "offenders",
							  "noose", "oasis", "cumin", "poxed", "wider", "stoic", "favor", "nurse",
							  "floss", "evens", "maxim", "nadir", "downs", "rodeo", "fungi", "verge"  ],
							[ "quarterly", "noisiness", "eagerness", "jailbreak",
							  "unlit", "radio", "eerie", "latte", "parka", "lunge", "salon", "exams",
							  "ailed", "lotto", "retro", "edens", "repel", "apron", "sheen", "loads"  ],
							[ "actresses", "deferrals", "venerates", "vegetates",
							  "chose", "roast", "solar", "entry", "farce", "ledge", "cobra", "plane",
							  "ebola", "exert", "lathe", "rhyme", "awful", "erred", "caper", "brawl"  ],
							[ "outercoat", "despaired", "alcoholic", "carpenter",
							  "undue", "erode", "chess", "atone", "trawl", "hello", "salvo", "swami",
							  "audio", "piece", "emote", "steep", "notch", "email", "sushi", "leave"  ],
							[ "quislings", "chattered", "fastballs", "acclaimed",
							  "unmet", "share", "issue", "grime", "circa", "spent", "conga", "excel",
							  "comma", "latte", "smith", "eject", "incas", "elite", "crepe", "niche"  ],
							[ "patrician", "terseness", "litigated", "goalposts",
							  "adapt", "reeve", "chump", "amaze", "swami", "sushi", "delta", "alive",
							  "orate", "lathe", "usage", "press", "oasis", "toads", "drain", "lairs"  ]		//150
							[ "gestation", "entranced", "engrossed", "handlooms",
							  "easel", "title", "traps", "ozone", "cutin", "refer", "amass", "rouse",
							  "asset", "delve", "acorn", "steer", "occur", "motif", "apron", "azure"  ],
							[ "censoring", "indemnity", "jambalaya", "regulated",
							  "eject", "share", "rotor", "nutty", "magma", "throb", "avail", "silky",
							  "enema", "untie", "titan", "rhyme", "admit", "eager", "arson", "allot"  ],
							[ "opulently", "telephony", "ordaining", "paramours",
							  "parch", "learn", "neigh", "loser", "tamer", "santa", "lemon", "arson",
							  "aorta", "ashen", "issue", "horse", "oaths", "ramen", "leach", "mason"  ],
							[ "aardvarks", "neverland", "obtaining", "patrician",
							  "arena", "dusty", "anode", "khaki", "redub", "sepia", "acorn", "avian",
							  "abets", "ready", "orate", "elide", "curbs", "addup", "avail", "onion"  ],
							[ "camellias", "immersing", "unclutter", "embroider",
							  "argue", "erase", "local", "award", "sheen", "total", "trait", "agree",
							  "magma", "reeve", "charm", "lodge", "inset", "elect", "toads", "apron"  ],
							[ "nightcaps", "celebrity", "indemnity", "scrubland",
							  "input", "hedge", "crept", "place", "basin", "style", "wagon", "gloat",
							  "cupid", "untie", "evade", "theme", "lobes", "nasty", "wager", "ghost"  ],
							[ "observers", "uncharged", "toothsome", "belatedly",
							  "boast", "entry", "vault", "rebar", "turbo", "asset", "veils", "swarm",
							  "enact", "artsy", "urban", "torch", "extra", "lords", "visor", "image"  ],
							[ "narrating", "hazelnuts", "temptress", "vertebral",
							  "again", "rotor", "trait", "nurse", "spire", "trump", "sorer", "abuts",
							  "enact", "tuner", "aorta", "these", "beset", "adieu", "spawn", "roust"  ],
							[ "malignant", "calliopes", "fishtanks", "tantalise",
							  "acrid", "ideal", "novel", "nasty", "khaki", "ninth", "llama", "skulk",
							  "aerie", "tidal", "vista", "loyal", "liken", "slain", "lasso", "abuse"  ],
							[ "baptising", "joltingly", "pedigrees", "readiness",
							  "about", "their", "salsa", "noses", "scare", "sushi", "wafer", "drake",
							  "elope", "deter", "lasso", "asset", "nests", "snaps", "widen", "frail"  ],		//160
							[ "gustatory", "nattering", "bedspread", "educators",
							  "ulcer", "terse", "tiara", "ropes", "swine", "edens", "cigar", "arena",
							  "decor", "curve", "alpha", "asset", "taste", "raise", "chair", "glean"  ],
							[ "ferocious", "dexterity", "tasteless", "weariness",
							  "ebola", "ocean", "inert", "usury", "karma", "sheet", "trail", "locus",
							  "evoke", "reaps", "etude", "tryst", "nukes", "serve", "tiler", "ascot"  ],
							[ "foothills", "incarnate", "radiances", "intensify",
							  "orbit", "their", "irons", "liken", "opera", "corgi", "train", "table",
							  "noble", "enter", "oaken", "santa", "stoic", "freer", "titan", "ambit"  ],
							[ "metabolic", "teetotals", "macintosh", "trackball",
							  "endup", "awoke", "opals", "icing", "dogma", "ennui", "debut", "urges",
							  "radio", "copse", "abide", "sight", "badge", "login", "doubt", "bagel"  ],
							[ "egomaniac", "governess", "longitude", "carjacker",
							  "grill", "money", "naval", "agree", "mango", "sting", "pleat", "trend",
							  "alien", "jolly", "virgo", "liege", "camps", "ennui", "piton", "evens"  ],
							[ "savouring", "uniformed", "wintering", "ceaseless",
							  "acute", "outer", "rocks", "ninja", "radii", "adept", "tutor", "mourn",
							  "exult", "smear", "canon", "staff", "larva", "sidle", "timer", "taupe"  ],
							[ "magnitude", "rehearsed", "depletion", "tightrope",
							  "atlas", "noone", "trace", "dogma", "douse", "rebel", "least", "video",
							  "igloo", "haste", "angle", "evade", "rider", "plumb", "liver", "addle"  ],
							[ "obstinacy", "newsdesks", "organized", "toothache",
							  "brick", "tongs", "noone", "china", "meter", "delta", "cacti", "blade",
							  "onion", "takes", "olive", "exams", "armed", "hotel", "cable", "clank"  ],
							[ "ancillary", "estranged", "mailboxes", "flashback",
							  "nasty", "issue", "large", "raved", "guava", "easel", "disco", "verge",
							  "loses", "style", "raves", "elder", "bugle", "chaos", "divan", "surge"  ],
							[ "perkiness", "genotypes", "dairymaid", "penniless",
							  "erode", "knave", "nests", "snail", "tiara", "solar", "album", "swami",
							  "ebola", "niece", "scare", "salvo", "lotus", "shall", "assay", "brave"  ],		//170
							[ "banefully", "despotism", "hairpiece", "scorchers",
							  "alert", "error", "under", "learn", "sigma", "elder", "corgi", "optic",
							  "cheer", "rotor", "drake", "runup", "haste", "raged", "clout", "rites"  ],
							[ "technopop", "rearrests", "feedstock", "ballistic",
							  "elite", "honey", "otter", "owner", "ample", "toyed", "paint", "lilac",
							  "alien", "leery", "tonne", "rarer", "shaft", "imply", "pulse", "islet"  ],
							[ "neediness", "hairstyle", "innovator", "scrimshaw",
							  "eyrie", "dwell", "nests", "stuff", "baron", "radio", "parka", "virgo",
							  "carve", "ideal", "sauna", "safer", "saber", "acrid", "pivot", "rural"  ],
							[ "serenaded", "opulently", "semifinal", "penthouse",
							  "earns", "essay", "avert", "endow", "theme", "corgi", "sushi", "drama",
							  "earls", "testy", "endup", "towel", "optic", "sneer", "sedan", "shawl"  ],
							[ "timesaver", "testiness", "nonprofit", "emptiness",
							  "index", "evens", "afoot", "elegy", "cello", "sharp", "metro", "sushi",
							  "midge", "taxes", "obese", "tryst", "nicks", "salsa", "mason", "tests"  ],
							[ "luxuriant", "valentine", "jessamine", "harboring",
							  "utter", "ulcer", "impel", "nerve", "lance", "roses", "alarm", "crown",
							  "antic", "borer", "parka", "liege", "ruler", "nines", "ascot", "adorn"  ],
							[ "justifies", "waterways", "rescinded", "amplified",
							  "utter", "tread", "frown", "elect", "inane", "lilac", "spurn", "rouse",
							  "matte", "lurid", "opera", "niche", "frill", "email", "shrew", "usury"  ],
							[ "vocalized", "charlatan", "taxidermy", "interlope",
							  "omega", "alert", "impel", "erupt", "circa", "swami", "cutie", "chasm",
							  "niece", "exalt", "plush", "later", "locus", "parka", "cocoa", "tiara"  ],
							[ "ratifying", "mentioned", "elopement", "passwords",
							  "agile", "idiot", "yacht", "nanny", "troll", "runup", "chasm", "learn",
							  "alibi", "slept", "canoe", "tryst", "outer", "drown", "cello", "apace"  ],
						  [ "operation", "adjoining", "readiness", "mouthwash",
							 "pleat", "raids", "toner", "onset", "awake", "synod", "pylon", "chaps",
							 "omega", "totes", "nosed", "ratio", "wears", "spawn", "pecan", "learn"  ]		//180
];  //180
