
var Solutions200 = [ [ "directory", "causation", "cartridge", "astronomy",
							  "inlet", "every", "tread", "ratio", "cocoa", "start", "swami", "icing",
							  "salve", "ratty", "extra", "dross", "nicks", "mocha", "swift", "amino"  ],
							[ "parochial", "territory", "gloomiest", "vindicate",
							  "abbey", "ocean", "hatch", "aback", "pupil", "rodeo", "sushi", "reaps",
							  "imbue", "doyen", "trade", "hiker", "caper", "taped", "strut", "stair"  ],
							[ "apologist", "rehearsal", "grayscale", "mangroves",
							  "preen", "laser", "gaunt", "shaft", "roger", "derby", "relic", "frail",
							  "abets", "goner", "usage", "tithe", "oared", "eager", "refer", "llama"  ],
							[ "throttled", "lambasted", "nominally", "oscillate",
							  "heron", "optic", "trust", "ember", "piano", "swami", "drama", "basil",
							  "strut", "ionic", "umbra", "throb", "lopes", "tiara", "debts", "aisle"  ],
							[ "sandiness", "insistent", "visionary", "lathering",
							  "atoll", "dodgy", "noble", "sworn", "khaki", "sushi", "blown", "freer",
							  "aloud", "hilly", "blown", "ennui", "rakes", "nears", "befit", "ocean"  ],
							[ "paleology", "hatchling", "sidelined", "alternate",
							  "atone", "elegy", "llama", "gloat", "swami", "liege", "khaki", "ochre",
							  "loose", "every", "aroma", "attic", "nasal", "trace", "knoll", "ashen"  ],
							[ "taxidermy", "anonymity", "retreated", "biography",
							  "adept", "inlet", "enter", "moody", "elide", "altar", "tiara", "tilde",
							  "ideal", "getat", "thorn", "rayon", "arena", "hoist", "totem", "allot"  ],
							[ "strapping", "heartless", "unclaimed", "unhealthy",
							  "timer", "ached", "prize", "nosed", "train", "petal", "ennui", "smite",
							  "nymph", "erred", "issue", "elder", "litup", "heart", "easel", "nails"  ],
							[ "deepening", "lifeboats", "workshops", "proclaims",
							  "ebola", "pesos", "nerds", "noble", "gecko", "smock", "sloth", "litup",
							  "roots", "crass", "rabbi", "sieve", "aegis", "macho", "salvo", "octet"  ],
							[ "headlocks", "telecasts", "pyromania", "zinfandel",
							  "elite", "digit", "outer", "khaki", "daily", "retro", "llama", "rabbi",
							  "icing", "fleet", "tease", "raise", "nadir", "edict", "larva", "ambit"  ],		//210
							[ "harlequin", "inherited", "millennia", "cirrhosis",
							  "amiss", "lemon", "qualm", "index", "swami", "steal", "croon", "chili",
							  "idiom", "resin", "addon", "moxie", "oasis", "irate", "cacti", "oxide"  ],
							[ "sailboard", "bedridden", "spotlight", "foodstuff",
							  "apnea", "laden", "ochre", "react", "stump", "yeast", "corgi", "tough",
							  "owned", "drawn", "heave", "enter", "testy", "fauna", "cited", "rouge"  ],
							[ "vasomotor", "patrimony", "porcupine", "charlatan",
							  "azure", "oddly", "opera", "outed", "curio", "tonic", "clasp", "adorn",
							  "hound", "reedy", "extra", "alder", "ascot", "apron", "charm", "acorn"  ],
							[ "tangerine", "orientate", "vicarages", "carefully",
							  "alpha", "genus", "rerun", "nerve", "corgi", "tiara", "cobra", "alone",
							  "aspen", "exams", "rarer", "niece", "uncut", "larva", "chart", "boost"  ],
							[ "imparting", "fantasist", "endangers", "earthworm",
							  "midge", "alter", "toads", "noone", "often", "larva", "wring", "cheer",
							  "audit", "their", "aroma", "slept", "whorl", "rotor", "wicks", "ideas"  ],
							[ "vestigial", "necklaces", "redirects", "academics",
							  "etude", "tongs", "giant", "apace", "ovate", "sushi", "dowse", "asset",
							  "churn", "dress", "abate", "tweak", "moors", "chaps", "drama", "waste"  ],
							[ "voicemail", "stateless", "kerchiefs", "yellowish",
							  "opium", "crept", "matte", "inane", "slope", "relic", "ennui", "aloof",
							  "elite", "limit", "toast", "erect", "wiser", "scowl", "email", "nooks"  ],
							[ "relegated", "kilohertz", "beverages", "lassitude",
							  "enter", "eyrie", "aorta", "ended", "aisle", "adore", "tibia", "twine",
							  "after", "surge", "radii", "audio", "tiara", "disco", "title", "built"  ],
							[ "washrooms", "canneries", "brewhouse", "resurrect",
							  "axing", "hated", "oasis", "mania", "rover", "renew", "piano", "luges",
							  "edict", "urged", "santa", "spawn", "rarer", "coven", "paler", "argue"  ],
							[ "rainbirds", "olfactory", "vocalists", "batteries",
							  "argon", "nerve", "intel", "drama", "virgo", "larva", "corgi", "unfit",
							  "augur", "tense", "trawl", "llama", "revel", "error", "crust", "refer"  ],		//220
							[ "absorbent", "marbelise", "sabotaged", "mouthwash",
							  "baton", "oasis", "baker", "north", "tiara", "ratio", "aroma", "abode",
							  "oaths", "tongs", "karma", "rehab", "water", "slant", "avail", "oboes"  ],
							[ "daredevil", "seventeen", "barbarian", "factotums",
							  "angle", "egret", "equip", "image", "extra", "throb", "bower", "ebola",
							  "augur", "treat", "usage", "piece", "tweet", "meter", "bleat", "wrote"  ],
							[ "weeknight", "marshland", "disrepute", "represent"
							  "ebony", "knell", "inapt", "hoops", "ennui", "foyer", "scamp", "audit",
							  "erode", "royal", "aroma", "tests", "sheaf", "nanny", "snail", "addon"  ]
];  //223
