
var Solutions400 = [ [ "merciless", "teledrama", "decisions", "bathwater",
							  "edged", "cones", "luges", "still", "grace", "sushi", "radii", "clean",
							  "argon", "hides", "guise", "solve", "aegis", "exams", "racer", "dream"  ],
							[ "allegedly", "abashedly", "mavericks", "motorcade",
							  "leant", "exert", "excel", "lairs", "media", "theme", "cacti", "pluck",
							  "ovate", "octet", "climb", "lists", "comet", "dodge", "copse", "cruel"  ],
							[ "sputtered", "meridians", "retaliate", "offshoots",
							  "proud", "tongs", "enter", "erred", "fable", "drama", "cacti", "inert",
							  "frown", "sides", "terse", "radii", "offed", "tibia", "chili", "clean"  ],
							[ "tarpaulin", "cirrhosis", "deerskins", "miscreant",
							  "adorn", "paste", "usage", "idiot", "caste", "laser", "dreck", "spoon",
							  "irons", "canoe", "alibi", "enter", "excel", "noses", "disco", "emoji"  ],
							[ "windpipes", "endearing", "cavorting", "dashboard",
							  "irons", "doggy", "input", "enter", "cobra", "retro", "midst", "lemon",
							  "among", "hasty", "piton", "terse", "occur", "robot", "molar", "demon"  ],
							[ "negotiate", "territory", "fisherman", "breakaway",
							  "expel", "oasis", "irked", "train", "chili", "thigh", "oiler", "sigma",
							  "ropes", "atlas", "knave", "diner", "ascot", "alibi", "onset", "lager"  ],
							[ "peacetime", "tenements", "bourgeois", "officiate",
							  "erode", "class", "tinge", "metro", "piano", "their", "algae", "swami",
							  "flora", "items", "nitre", "evoke", "input", "trade", "aisle", "graft"  ],
							[ "collusion", "undergoes", "porcupine", "marijuana",
							  "ought", "lunar", "splat", "opals", "salvo", "tonic", "tramp", "again",
							  "argon", "inter", "learn", "taste", "upset", "nylon", "twang", "amaze"  ],
							[ "seahorses", "vampirism", "decreased", "carnelian",
							  "exert", "haste", "rides", "exalt", "matte", "occur", "omega", "flake",
							  "abets", "nitre", "drama", "situp", "limbo", "attic", "offer", "exams"  ],
							[ "disguised", "levelling", "pluralism", "strapping",
							  "intel", "great", "igloo", "ebola", "easel", "easer", "crawl", "rains",
							  "title", "allot", "loose", "ovate", "peeve", "nests", "coral", "alien"  ],		//410
							[ "grievance", "necessary", "denounces", "seasoning",
							  "reeve", "entry", "apple", "china", "taste", "rodeo", "lemon", "solve",
							  "event", "seedy", "prise", "erase", "noter", "nosed", "loses", "molar"  ],
							[ "parasites", "bawdiness", "wearingly", "genealogy",
							  "along", "avert", "intel", "ember", "clime", "deter", "radon", "swirl",
							  "evoke", "eight", "tibia", "lurid", "lucid", "grist", "resin", "dries"  ],
							[ "pluralism", "gradually", "marketers", "saddening",
							  "loser", "range", "lemur", "silts", "aloha", "speak", "visit", "steer",
							  "arson", "dirge", "molar", "resod", "neaps", "noose", "vista", "steal"  ],
							[ "terabytes", "flagpoles", "offshoots", "acridness",
							  "elves", "asset", "yogis", "emoji", "grief", "tides", "pluto", "apart",
							  "caves", "inset", "growl", "sting", "night", "shied", "piano", "usage"  ],
							[ "workforce", "bawdiness", "inhabited", "addictive",
							  "onset", "knoll", "obese", "crowd", "login", "polka", "corgi", "there",
							  "disco", "intel", "ebola", "ended", "tulip", "vigil", "cutin", "reeds"  ],
							[ "lamplight", "utilities", "analogies", "headgears",
							  "anode", "prism", "inter", "homey", "deign", "wheel", "prong", "adage",
							  "emoji", "dream", "tempt", "royal", "endow", "raise", "plait", "ovate"  ],
							[ "horoscope", "telegraph", "redolence", "frustrate",
							  "omega", "onset", "cider", "prong", "dance", "salvo", "paste", "lyric",
							  "reeds", "scant", "drove", "rogue", "rides", "tonal", "paler", "syrup"  ],
							[ "deductive", "advocated", "messaging", "tribalism",
							  "extra", "upset", "teach", "viral", "chute", "lotus", "debug", "apron",
							  "rites", "blast", "acrid", "hello", "local", "shunt", "drama", "barge"  ],
							[ "implement", "leverages", "eightball", "backpacks",
							  "maple", "loyal", "mopes", "noone", "corgi", "death", "scrub", "local",
							  "apply", "knell", "prose", "siege", "arced", "karma", "salsa", "recce"  ],
							[ "snowdrift", "canoodles", "disrepute", "coagulate",
							  "nadir", "wired", "roger", "famed", "swami", "super", "setup", "evict",
							  "order", "gored", "gamma", "radio", "loses", "tramp", "steed", "twice"  ],		//420
							[ "tailoring", "liberated", "treatment", "toothless",
							  "amiss", "liege", "roast", "noise", "diver", "ninja", "storm", "grown",
							  "olive", "taste", "alibi", "there", "laden", "seven", "sigma", "ozone"  ],
							[ "indemnity", "cementing", "uncannily", "polyester",
							  "noted", "excel", "novel", "tenet", "adorn", "plaza", "pecan", "swirl",
							  "optic", "yodel", "venue", "lithe", "stamp", "ebola", "posit", "cairn"  ],
							[ "capuchins", "beginners", "activists", "fabricate",
							  "audit", "upped", "holds", "nines", "ionic", "emoji", "cacti", "agent",
							  "addup", "rated", "lunge", "sushi", "clime", "tango", "chain", "cheer"  ],
							[ "secession", "bluntness", "obstacles", "firepower",
							  "evade", "erect", "sauna", "outer", "thumb", "overt", "civic", "lithe",
							  "irate", "eject", "until", "apron", "outdo", "elude", "colon", "votes"  ],
							[ "captained", "pollution", "terrorise", "mannerism",
							  "adore", "terse", "inlet", "extra", "elope", "eider", "stair", "alias",
							  "amour", "niece", "lotto", "trawl", "reeve", "scold", "shaft", "amino"  ],
							[ "glitziest", "strapless", "reconcile", "responder",
							  "loner", "tried", "inapt", "sauna", "inane", "hello", "lilac", "cabal",
							  "ennui", "pared", "adult", "tiara", "neigh", "email", "local", "lobes"  ],
							[ "liberated", "navigator", "signalled", "bloodbath",
							  "inane", "erect", "amass", "edens", "khaki", "resin", "vital", "sense",
							  "lease", "overt", "arena", "sushi", "baker", "traps", "vista", "tango"  ],
							[ "barbarism", "casserole", "residency", "hyperlink",
							  "amuse", "bogus", "rapid", "shaft", "choke", "sushi", "purse", "cubic",
							  "young", "evens", "plaza", "dates", "locus", "nooks", "pacer", "rebel"  ],
							[ "dispersal", "crescendo", "castanets", "velodrome",
							  "irons", "peaks", "rehab", "armed", "vodka", "leapt", "titan", "stint",
							  "ebola", "oasis", "humor", "bides", "rival", "media", "taste", "tried"  ],
							[ "embitters", "gestating", "filthiest", "televised",
							  "moods", "idyll", "timid", "ripup", "sushi", "tweet", "khaki", "perks",
							  "ebony", "easel", "maple", "depot", "inset", "ensue", "kaput", "apron"  ],		//430
							[ "hairweave", "stockpile", "omissions", "carjacked",
							  "anger", "rally", "ender", "venal", "totem", "years", "sushi", "align",
							  "angel", "jerky", "donut", "relic", "catty", "extra", "sharp", "spill"  ],
							[ "paltriest", "vagabonds", "ceaseless", "balaclava",
							  "anger", "talon", "inept", "satyr", "goose", "class", "phial", "takes",
							  "angel", "apron", "extra", "terra", "logic", "viola", "patio", "irked"  ],
							[ "camisoles", "celebrity", "offshoots", "haphazard",
							  "anger", "idled", "often", "emote", "staff", "yetis", "ratio", "grout",
							  "angel", "hired", "trove", "niece", "zesty", "roast", "rigor", "trout"  ],
							[ "achieving", "uppermost", "immolates", "reprobate",
							  "clung", "inter", "votes", "needy", "axiom", "nitro", "circa", "rinse",
							  "erupt", "rigor", "twerp", "style", "brain", "twist", "carom", "rents"  ],
							[ "healthier", "ostracism", "alternate", "gazetteer",
							  "elope", "leggy", "haiku", "epoch", "stall", "siege", "arson", "tract",
							  "among", "enemy", "irons", "usher", "tests", "erase", "attic", "snaps"  ],
							[ "disgraced", "plummeted", "mendicant", "camelback",
							  "icing", "gloss", "aloof", "enter", "shale", "duped", "optic", "blown",
							  "amino", "edges", "octal", "forum", "based", "champ", "ombre", "trope"  ],
							[ "posterior", "declining", "immensely", "misstated",
							  "orate", "theme", "rebar", "oiler", "groom", "evade", "poses", "trial",
							  "irate", "siege", "bulge", "rural", "algae", "ebola", "piton", "scion"  ],
							[ "gemstones", "chastened", "clattered", "probation",
							  "elide", "scent", "orate", "erase", "pearl", "cleat", "siege", "urine",
							  "raise", "bleat", "awash", "edens", "topic", "ovate", "sauce", "elite"  ],
							[ "blemished", "dislodged", "finishing", "lambasted",
							  "leggy", "meter", "sward", "elite", "rabbi", "radii", "shush", "widen",
							  "aught", "buyer", "alibi", "dwell", "sorer", "embed", "sowed", "undue"  ],
							[ "interlope", "pastiches", "royalties", "catchiest",
							  "nines", "ensue", "lithe", "purge", "intro", "manga", "chant", "broke",
							  "aunts", "caste", "terra", "event", "idiom", "satin", "cubic", "alone"  ],		//440
							[ "scoldings", "headboard", "snowboard", "outsmarts",
							  "caber", "lined", "idiot", "gable", "aspen", "screw", "gecko", "spear",
							  "urban", "shred", "imbue", "tweed", "amass", "taper", "gusto", "clear"  ],
							[ "maladroit", "panellist", "seniority", "loopholes",
							  "aglow", "ardor", "roost", "ideal", "tithe", "swami", "bower", "asset",
							  "oiled", "power", "omega", "tilde", "oaths", "extra", "brawl", "wasps"  ],
							[ "reservoir", "rosewater", "flowerpot", "collector",
							  "ether", "erred", "verge", "icing", "metal", "allow", "super", "gusto",
							  "other", "lurid", "rhino", "eagle", "comma", "octal", "sigma", "paste"  ],
							[ "factotums", "integrate", "jobseeker", "laundries",
							  "among", "toast", "tests", "moron", "banjo", "nails", "sidle", "abase",
							  "aroma", "night", "siren", "sense", "robin", "ennui", "stair", "draft"  ],
							[ "electrons", "sandboxes", "compelled", "reformist",
							  "litre", "caret", "react", "noone", "dingo", "twerp", "novel", "twice",
							  "enter", "overt", "aroma", "tweed", "midst", "singe", "nitro", "voice"  ],
							[ "dispersed", "storyline", "fertility", "painfully",
							  "inapt", "putty", "rites", "error", "crude", "reset", "anvil", "argot",
							  "avast", "nutty", "tarot", "sorer", "ulcer", "lauds", "avail", "vegan"  ],
							[ "converged", "warranted", "miniscule", "mousetrap",
							  "ochre", "verse", "reeve", "elect", "sushi", "ennui", "colic", "bevel",
							  "other", "suede", "enema", "enter", "taste", "arson", "cabin", "levee"  ],
							[ "stuttered", "rebooting", "coriander", "endowment",
							  "tiled", "tenor", "edged", "exams", "nitro", "sushi", "bacon", "ozone",
							  "nylon", "order", "glade", "disco", "minus", "notes", "bloat", "crown"  ],
							[ "blossomed", "ascertain", "recycling", "testiness",
							  "looks", "stage", "optic", "extra", "cache", "rusty", "coral", "olden",
							  "ebola", "taste", "totes", "chafe", "nicer", "sects", "clout", "radii"  ],
							[ "communion", "seashells", "tolerable", "backhands",
							  "ocean", "mushy", "needs", "onion", "outdo", "noose", "panda", "novel",
							  "abets", "kinky", "exile", "sends", "acorn", "ditto", "pence", "naval"  ],		//450
							[ "bedazzled", "staggered", "landmarks", "sincerely",
							  "eaten", "above", "zests", "emoji", "media", "ahead", "circa", "cluck",
							  "intro", "canoe", "scoot", "sting", "rumba", "ledge", "cycle", "rouge"  ],
							[ "goofiness", "mentoring", "adamantly", "algorithm",
							  "oaken", "fused", "nests", "snide", "trend", "rearm", "pecan", "wheel",
							  "likes", "owned", "snipe", "slept", "inter", "hyena", "power", "clean"  ],
							[ "obscurant", "carnelian", "opposites", "imitating",
							  "bulky", "crept", "ramps", "nudge", "tulip", "mango", "swami", "evoke",
							  "melee", "tryst", "media", "sheen", "totem", "nylon", "steal", "aroma"  ],
							[ "quarreled", "magnetite", "legwarmer", "absurdist",
							  "unlit", "royal", "enact", "eject", "trove", "straw", "sheer", "grime",
							  "bully", "until", "arena", "titan", "dates", "scour", "sight", "exist"  ],
							[ "coproduce", "eyelashes", "underfund", "allowance",
							  "orate", "rites", "dress", "close", "demon", "those", "motif", "prawn",
							  "leapt", "obeys", "ebony", "steal", "audit", "cameo", "mopes", "trade"  ],
							[ "cartilage", "irritable", "redressed", "scoreless",
							  "alert", "toned", "loser", "grind", "brace", "drier", "debts", "close",
							  "clean", "rated", "skier", "radii", "lubed", "swami", "dacha", "broil"  ],
							[ "bilateral", "physicist", "tribalism", "approving",
							  "ionic", "ample", "ensue", "aroma", "timer", "redub", "troll", "nails",
							  "pinup", "recce", "sloth", "exams", "voter", "nomad", "tonic", "omits"  ],
							[ "slandered", "carcasses", "witnesses", "reconnect",
							  "linen", "noise", "easel", "equal", "chili", "radon", "tides", "awoke",
							  "ennui", "ounce", "sauna", "lilac", "nicer", "child", "toads", "diode"  ],
							[ "crossword", "notations", "chrysalis", "tormented",
							  "rains", "steer", "walls", "resin", "thigh", "ritzy", "cobra", "corgi",
							  "oxide", "miser", "lasso", "santa", "noter", "exist", "cacti", "baron"  ],
							[ "geologist", "novelties", "backtrack", "astrodome",
							  "eerie", "lance", "genie", "sites", "manga", "stack", "outer", "tonic",
							  "sarin", "reeve", "nitro", "ensue", "dumps", "mania", "octet", "tense"  ],		//460
							[ "recollect", "magnifies", "kerchiefs", "hatchback",
							  "enact", "oiler", "loads", "credo", "large", "stoic", "cacti", "aloof",
							  "avail", "cater", "arena", "sworn", "bulls", "cargo", "chaff", "chose"  ],
							[ "kingmaker", "networked", "badminton", "saliently",
							  "imbue", "great", "agree", "ended", "cobra", "scram", "woman", "virgo",
							  "amble", "inept", "ridge", "endow", "nicks", "labor", "waver", "merge"  ],
							[ "thickness", "immensely", "imperiled", "toothsome",
							  "halon", "carer", "novel", "since", "forum", "salve", "khaki", "dunce",
							  "ogler", "tuner", "venom", "liege", "sifts", "moral", "kudos", "annul"  ],
							[ "incubator", "varieties", "vouchsafe", "territory",
							  "nitre", "usage", "awoke", "ocean", "taboo", "medic", "abets", "scuff",
							  "extra", "reeve", "opera", "ennui", "totem", "robed", "asset", "elude"  ],
							[ "flippancy", "seclusion", "mortgaged", "wearisome",
							  "linen", "prime", "await", "churn", "outdo", "egret", "kappa", "drone",
							  "ennui", "rinse", "acute", "tonal", "slope", "motor", "kudos", "photo"  ],
							[ "mousetrap", "violinist", "fieldwork", "barbarism",
							  "obese", "scaly", "their", "agony", "ennui", "stall", "elbow", "tiger",
							  "arena", "beefy", "emoji", "royal", "reeks", "santa", "eaten", "bogus"  ],
							[ "testifies", "immersing", "teetotals", "embellish",
							  "enter", "theft", "frost", "exits", "alive", "avert", "covet", "regal",
							  "matte", "egret", "odium", "taste", "llama", "snipe", "corps", "vegan"  ],
							[ "chrysalis", "gestating", "calcifies", "discharge",
							  "hyena", "yetis", "ample", "inane", "aloha", "topic", "stuff", "alive",
							  "inert", "craps", "phase", "eject", "avast", "group", "scant", "union"  ],
							[ "epitomise", "retracted", "photocopy", "incorrect",
							  "photo", "tests", "meter", "smart", "trash", "ought", "lilac", "group",
							  "nooks", "oboes", "trace", "rotor", "ratio", "clang", "logic", "loose"  ],
							[ "hazelnuts", "timesaver", "joyriders", "electrons",
							  "axing", "eased", "nasal", "train", "gusto", "eider", "mated", "diner",
							  "lairs", "caged", "swami", "lance", "rogue", "nosed", "media", "tinge"  ],		//470
							[ "rectitude", "perennial", "unblocked", "afternoon",
							  "earth", "teens", "totes", "delta", "often", "scowl", "optic", "drake",
							  "farce", "ethos", "tilde", "shave", "nooks", "outdo", "olden", "tiara"  ],
							[ "paragraph", "inhabited", "mastodons", "escalator",
							  "aroma", "atlas", "rocks", "phial", "mocha", "reset", "cloud", "chain",
							  "shoal", "amass", "cairn", "salsa", "armor", "orcas", "cacti", "orate"  ],
							[ "negatives", "kindliest", "apologist", "staggered",
							  "erect", "audit", "inked", "erase", "runup", "twirl", "cling", "crops",
							  "trend", "getat", "khaki", "dread", "egret", "ennui", "cacti", "idols"  ],
							[ "stovepipe", "barefaced", "victimise", "tectonics",
							  "torso", "verve", "peons", "plead", "cacti", "eject", "alarm", "earns",
							  "error", "those", "opera", "sidle", "niche", "cache", "arena", "aerie"  ],
							[ "shadowbox", "weaseling", "millennia", "teammates",
							  "hedge", "darts", "world", "orcas", "swami", "natal", "baron", "sushi",
							  "elder", "meets", "recce", "dusts", "arson", "exact", "basil", "risen"  ],
							[ "cosmetics", "ramrodded", "birthrate", "lampshade",
							  "odour", "magma", "tempo", "canon", "corgi", "swept", "alter", "afoot",
							  "among", "parka", "manga", "owner", "hacks", "dirge", "award", "those"  ],
							[ "terminate", "medicates", "cardinals", "patterned",
							  "eerie", "munch", "nicks", "toads", "cobra", "erred", "felon", "usual",
							  "apron", "teeth", "cease", "sushi", "recce", "ember", "fauna", "louse"  ],
							[ "boondocks", "regressed", "irrigated", "hesitated",
							  "outdo", "nervy", "otter", "kneel", "tenor", "chili", "mania", "chide",
							  "enter", "irony", "there", "ruler", "antic", "ennui", "mucus", "naive"  ],
							[ "downright", "accessing", "widowhood", "barbarity",
							  "orate", "needy", "inlet", "hurry", "swami", "ratio", "filth", "tempo",
							  "abate", "beefy", "lyric", "thyme", "riser", "trait", "fetes", "lemon"  ],
							[ "redefines", "reverence", "passwords", "tectonics",
							  "edged", "essay", "inset", "error", "circa", "evens", "macho", "doled",
							  "edges", "today", "spree", "three", "niche", "curse", "midge", "colic"  ],		//480
							[ "bystander", "unsighted", "harshness", "heretical",
							  "yetis", "tarry", "needs", "elves", "tiara", "obeys", "flown", "reaps",
							  "enter", "essay", "elven", "sushi", "intro", "amaze", "firth", "orate"  ],
							[ "discarded", "decrypted", "scapegoat", "waitstaff",
							  "intel", "cared", "rabid", "exist", "tunic", "addup", "twang", "llama",
							  "after", "tiled", "beige", "deter", "tetra", "fined", "tulip", "awake"  ],
							[ "unnoticed", "ballerina", "undamaged", "hairstyle",
							  "nooks", "ogled", "incur", "empty", "raven", "aorta", "plaza", "stale",
							  "atoll", "resod", "copra", "royal", "terra", "liver", "poser", "again"  ],
							[ "garnering", "liberates", "miniscule", "gardening",
							  "alien", "noise", "recap", "nicer", "swami", "sushi", "havoc", "drill",
							  "alibi", "dense", "cacti", "purse", "nests", "neaps", "hydra", "voice"  ],
							[ "custodial", "additives", "assertion", "magnolias",
							  "usage", "tense", "decks", "aloha", "earns", "halve", "erupt", "nitro",
							  "again", "niece", "crowd", "swami", "leech", "aural", "ennui", "untie"  ],
							[ "uniformed", "agonising", "marathons", "abdicated",
							  "nears", "flout", "recap", "equal", "guava", "tetra", "leach", "shown",
							  "bravo", "inset", "clung", "pylon", "aught", "enact", "loses", "acorn"  ],
							[ "contorted", "patrolman", "personage", "overnight",
							  "organ", "teens", "river", "ended", "stake", "ethos", "coven", "bring",
							  "vague", "rents", "vodka", "radar", "issue", "heath", "cabal", "voila"  ],
							[ "irradiate", "carpentry", "railroads", "herniated",
							  "rates", "avail", "ionic", "tenet", "omega", "natal", "piano", "ached",
							  "extra", "nasal", "ninja", "cutup", "adorn", "erect", "prawn", "abhor"  ],
							[ "downshift", "varyingly", "terrified", "enshrined",
							  "overt", "nasal", "hoped", "fined", "naive", "cheer", "snuff", "exude",
							  "needs", "hotel", "panda", "daddy", "ionic", "exile", "sheen", "usual"  ],
							[ "revolving", "undefined", "throttled", "nerveless",
							  "elect", "opted", "vinyl", "nomad", "mulch", "nitro", "erect", "naive",
							  "event", "voted", "nomen", "ledge", "lemon", "splat", "ennui", "elite"  ],		//490
							[ "hopscotch", "dealmaker", "etymology", "sociology",
							  "ovens", "stale", "oiled", "close", "smart", "realm", "mogul", "doing",
							  "opera", "issue", "loose", "dwell", "loser", "guava", "media", "glide"  ],
							[ "cauterise", "chastened", "upcountry", "potentate",
							  "alert", "their", "rogue", "salvo", "stump", "yahoo", "pecan", "nicer",
							  "obese", "enter", "gulch", "ebons", "testy", "touch", "pence", "cycle"  ],
							[ "tolerance", "recruiter", "neediness", "birthdate",
							  "ovate", "event", "about", "canoe", "orate", "poked", "sworn", "suits",
							  "irate", "treat", "ounce", "their", "droop", "track", "sushi", "olive"  ],
							[ "malicious", "reproduce", "tarnishes", "concerned",
							  "alone", "inept", "ingot", "usage", "sauna", "satin", "salts", "aerie",
							  "ozone", "cleat", "glade", "their", "rusts", "erupt", "stand", "lyric"  ],
							[ "schedules", "imprudent", "landlines", "lampposts",
							  "clout", "elfin", "usage", "exalt", "china", "shred", "swami", "adage",
							  "aloof", "piton", "alarm", "enter", "orcas", "trier", "stand", "again"  ]
];  //495
