
var Solutions400 = [ [ "merciless", "teledrama", "decisions", "bathwater",
							  "edged", "cones", "luges", "still", "grace", "sushi", "radii", "clean",
							  "argon", "hides", "guise", "solve", "aegis", "exams", "racer", "dream"  ],
							[ "allegedly", "abashedly", "mavericks", "motorcade",
							  "leant", "exert", "excel", "lairs", "media", "theme", "cacti", "pluck",
							  "ovate", "octet", "climb", "lists", "comet", "dodge", "copse", "cruel"  ],
							[ "sputtered", "meridians", "retaliate", "offshoots",
							  "proud", "tongs", "enter", "erred", "fable", "drama", "cacti", "inert",
							  "frown", "sides", "terse", "radii", "offed", "tibia", "chili", "clean"  ],
							[ "tarpaulin", "cirrhosis", "deerskins", "miscreant",
							  "adorn", "paste", "usage", "idiot", "caste", "laser", "dreck", "spoon",
							  "irons", "canoe", "alibi", "enter", "excel", "noses", "disco", "emoji"  ],
							[ "windpipes", "endearing", "cavorting", "dashboard",
							  "irons", "doggy", "input", "enter", "cobra", "retro", "midst", "lemon",
							  "among", "hasty", "piton", "terse", "occur", "robot", "molar", "demon"  ],
							[ "negotiate", "territory", "fisherman", "breakaway",
							  "expel", "oasis", "irked", "train", "chili", "thigh", "oiler", "sigma",
							  "ropes", "atlas", "knave", "diner", "ascot", "alibi", "onset", "lager"  ],
							[ "peacetime", "tenements", "bourgeois", "officiate",
							  "erode", "class", "tinge", "metro", "piano", "their", "algae", "swami",
							  "flora", "items", "nitre", "evoke", "input", "trade", "aisle", "graft"  ],
							[ "collusion", "undergoes", "porcupine", "marijuana",
							  "ought", "lunar", "splat", "opals", "salvo", "tonic", "tramp", "again",
							  "argon", "inter", "learn", "taste", "upset", "nylon", "twang", "amaze"  ],
							[ "seahorses", "vampirism", "decreased", "carnelian",
							  "exert", "haste", "rides", "exalt", "matte", "occur", "omega", "flake",
							  "abets", "nitre", "drama", "situp", "limbo", "attic", "offer", "exams"  ],
							[ "disguised", "levelling", "pluralism", "strapping",
							  "intel", "great", "igloo", "ebola", "easel", "easer", "crawl", "rains",
							  "title", "allot", "loose", "ovate", "peeve", "nests", "coral", "alien"  ],		//410
							[ "grievance", "necessary", "denounces", "seasoning",
							  "reeve", "entry", "apple", "china", "taste", "rodeo", "lemon", "solve",
							  "event", "seedy", "prise", "erase", "noter", "nosed", "loses", "molar"  ],
							[ "parasites", "bawdiness", "wearingly", "genealogy",
							  "along", "avert", "intel", "ember", "clime", "deter", "radon", "swirl",
							  "evoke", "eight", "tibia", "lurid", "lucid", "grist", "resin", "dries"  ],
							[ "pluralism", "gradually", "marketers", "saddening",
							  "loser", "range", "lemur", "silts", "aloha", "speak", "visit", "steer",
							  "arson", "dirge", "molar", "resod", "neaps", "noose", "vista", "steal"  ],
							[ "terabytes", "flagpoles", "offshoots", "acridness",
							  "elves", "asset", "yogis", "emoji", "grief", "tides", "pluto", "apart",
							  "caves", "inset", "growl", "sting", "night", "shied", "piano", "usage"  ],
							[ "workforce", "bawdiness", "inhabited", "addictive",
							  "onset", "knoll", "obese", "crowd", "login", "polka", "corgi", "there",
							  "disco", "intel", "ebola", "ended", "tulip", "vigil", "cutin", "reeds"  ],
							[ "lamplight", "utilities", "analogies", "headgears",
							  "anode", "prism", "inter", "homey", "deign", "wheel", "prong", "adage",
							  "emoji", "dream", "tempt", "royal", "endow", "raise", "plait", "ovate"  ],
							[ "horoscope", "telegraph", "redolence", "frustrate",
							  "omega", "onset", "cider", "prong", "dance", "salvo", "paste", "lyric",
							  "reeds", "scant", "drove", "rogue", "rides", "tonal", "paler", "syrup"  ],
							[ "deductive", "advocated", "messaging", "tribalism",
							  "extra", "upset", "teach", "viral", "chute", "lotus", "debug", "apron",
							  "rites", "blast", "acrid", "hello", "local", "shunt", "drama", "barge"  ],
							[ "implement", "leverages", "eightball", "backpacks",
							  "maple", "loyal", "mopes", "noone", "corgi", "death", "scrub", "local",
							  "apply", "knell", "prose", "siege", "arced", "karma", "salsa", "recce"  ],
							[ "snowdrift", "canoodles", "disrepute", "coagulate",
							  "nadir", "wired", "roger", "famed", "swami", "super", "setup", "evict",
							  "order", "gored", "gamma", "radio", "loses", "tramp", "steed", "twice"  ]	//420
];  //500
