
var Solutions = [ [ "packaging", "jalapenos", "paddocked", "tactician",
						  "asset", "kneal", "glide", "nitro", "umbra", "bored", "panic", "large",
						  "aisle", "total", "intra", "ebola", "crumb", "arbor", "pulse", "narco"  ],
						[ "taquerias", "handstand", "cabdriver", "cameramen",
						  "alike", "unmet", "reset", "anger", "dacha", "riled", "swami", "grime",
						  "axiom", "eject", "sigma", "tired", "ardor", "excel", "sight", "align"  ],
						[ "zeppelins", "organised", "nanometer", "cabinetry",
						  "exact", "polar", "lease", "night", "tibia", "radio", "shale", "arise",
						  "avail", "inter", "anger", "extra", "enter", "robed", "swami", "abide"  ],
						[ "vacillate", "quadratic", "ideations", "abidingly",
						  "actor", "items", "label", "toyed", "sated", "sepia", "swami", "union",
						  "bathe", "dares", "bayou", "laded", "noses", "litup", "sauna", "alibi"  ],
						[ "tablefuls", "abhorrent", "magnetise", "valuables",
						  "aided", "laser", "faced", "loins", "karma", "sheen", "ascot", "gross",
						  "aides", "under", "climb", "disco", "bikes", "eyrie", "augur", "crown"  ],
						[ "nanometer", "yearnings", "hackneyed", "zirconias",
						  "ample", "oiled", "eerie", "exult", "magma", "dreck", "cadre", "raise",
						  "impel", "creed", "route", "enter", "named", "algae", "corgi", "doing"  ],
						[ "magnetise", "yellowish", "yesterday", "lacerated",
						  "alias", "nines", "total", "splay", "louse", "scent", "taper", "rasta",
						  "align", "eases", "tilde", "loyal", "atlas", "exude", "throw", "poses"  ],
						[ "imagineer", "keystroke", "unabashed", "qualifies",
						  "madam", "godly", "north", "eager", "cutin", "throb", "lodes", "brink",
						  "undid", "lumpy", "rogue", "hires", "facet", "enter", "labor", "drink"  ],
						[ "sacrilege", "kabbalist", "narcotics", "unashamed",
						  "atone", "reefs", "leafs", "gaper", "ultra", "sonic", "crust", "magic",
						  "noose", "sheds", "alpha", "shrub", "alums", "eaten", "camel", "urges"  ],
						[ "rainbirds", "racketeer", "vaporizer", "magnetise",
						  "award", "niece", "incas", "drive", "salsa", "ditto", "sushi", "exude",
						  "awake", "nudge", "china", "steak", "tased", "splat", "swept", "sauce"  ],		//10
						[ "keystones", "ecologies", "lacerated", "magnolias",
						  "edged", "smear", "occur", "envoy", "aorta", "slate", "arena", "image", 
						  "angle", "nadir", "civic", "royal", "leaps", "aorta", "aping", "erase"  ],
						[ "saccharin", "dachshund", "vapidness", "idolators",
						  "abate", "cinch", "asset", "iller", "aorta", "ennui", "doyen", "amass",
						  "drawn", "leech", "salsa", "torch", "trace", "rerun", "death", "yearn"  ],
						[ "tampering", "palisades", "sailplane", "zirconias",
						  "argon", "patty", "roses", "napes", "alpha", "steal", "vital", "spurn", 
						  "ingot", "canny", "sepia", "sushi", "nears", "ample", "vista", "truce"  ],
						[ "rallyists", "vanishing", "kinswomen", "gamblings",
						  "agile", "lousy", "incur", "tubed", "swami", "traps", "disco", "acute",
						  "adieu", "beefy", "cobra", "radii", "inset", "guava", "death", "spurn"  ],
						[ "garrotted", "easygoing", "washboard", "halfpence",
						  "attic", "races", "touch", "extra", "opera", "hatch", "hello", "diver",
						  "antic", "focus", "ultra", "heavy", "epoch", "cheat", "hydro", "liven"  ],
						[ "quibbling", "hamburger", "unadvised", "obscurity",
						  "ulnas", "boots", "lemur", "nymph", "crown", "rigid", "ennui", "barge",
						  "banjo", "costs", "mamba", "rehab", "recur", "thong", "ember", "nurse"  ],
						[ "calibrate", "illegible", "imbecilic", "kinswoman",
						  "ample", "intel", "rains", "these", "madam", "curve", "sushi", "alibi",
						  "input", "shell", "ideal", "suede", "olmec", "adder", "swami", "still"  ],
						[ "rallyings", "jadedness", "saddening", "sacrament",
						  "aspen", "liege", "inert", "grove", "salsa", "synod", "baron", "onion",
						  "apple", "range", "ebola", "there", "mists", "nylon", "brown", "rains"  ],
						[ "keepsakes", "backdraft", "familiars", "jailhouse",
						  "ergot", "porch", "amass", "eerie", "omega", "ennui", "sushi", "flair",
						  "anger", "latch", "aorta", "speak", "ozone", "sheen", "safer", "scarf"  ],
						[ "factually", "sanctions", "tapeworms", "quintuple",
						  "after", "terse", "alpha", "least", "gamma", "dirge", "salvo", "alarm",
						  "utter", "nurse", "plaza", "attic", "urged", "lemur", "swami", "learn"  ],		//20
						[ "unassured", "garnetted", "variances", "quibbling",
						  "noble", "staid", "utter", "ember", "karma", "sushi", "apron", "spice",
						  "umbra", "bleed", "tibia", "rerun", "likes", "nerds", "asset", "raise"  ],
						[ "pachyderm", "hairstyle", "abutments", "handballs",
						  "ahead", "hedge", "doted", "robin", "plumb", "reset", "clime", "depot",
						  "amend", "dodge", "tibia", "donor", "asper", "lauds", "cadet", "impel"  ],
						[ "danceable", "nameplate", "eccentric", "waistband",
						  "abuse", "crepe", "alert", "latte", "civic", "purge", "cleat", "alibi",
						  "acute", "suede", "extra", "there", "bicep", "never", "crawl", "evict"  ],
						[ "gashouses", "hairiness", "factually", "sandflies",
						  "arrow", "heave", "utter", "erred", "dogma", "eject", "parka", "civil",
						  "aorta", "dowse", "terra", "radar", "ledge", "eagle", "pecan", "roves"  ],
						[ "variables", "yodelling", "panhandle", "varieties",
						  "addup", "ivory", "boast", "edits", "aorta", "perch", "radon", "prowl",
						  "audio", "imply", "amino", "taste", "tramp", "error", "repel", "drown"  ],
						[ "quotients", "sandpaper", "ramifying", "quaintest",
						  "until", "tarry", "ethos", "tonal", "opera", "ennui", "dingy", "acorn",
						  "utter", "inlay", "henna", "salad", "trope", "stern", "drama", "noone"  ],
						[ "mainsails", "backbeats", "hairstyle", "kerfuffle",
						  "alien", "natal", "amock", "leery", "comma", "tutor", "ambit", "steal",
						  "evict", "final", "opera", "kayak", "facet", "limit", "aisle", "bleat"  ],
						[ "waistline", "venerable", "jestingly", "ecumenism",
						  "adieu", "snake", "lunch", "nicks", "spare", "sprat", "pagan", "avail",
						  "china", "mauve", "niche", "haste", "nests", "stair", "plaza", "grail"  ],
						[ "idiomatic", "washables", "daydreams", "waistline",
						  "droll", "opera", "asked", "input", "dacha", "stead", "cutie", "idiom",
						  "anode", "salsa", "kappa", "ditch", "lodes", "niche", "climb", "trite"  ],
						[ "vampirish", "jaywalked", "callbacks", "racetrack",
						  "alive", "peers", "revue", "stood", "comma", "penal", "fauna", "trick",
						  "abide", "edens", "viola", "endow", "recap", "cumin", "fetal", "unite"  ],		//30
						[ "abdicable", "wallabies", "obstetric", "calculate",
						  "beard", "islet", "abase", "lords", "shrub", "shout", "taunt", "radii",
						  "avail", "cadet", "aorta", "easel", "loses", "torso", "throb", "undue"  ],
						[ "gastritis", "taxpaying", "dadaistic", "tawdriest",
						  "aloha", "these", "inlet", "irate", "koala", "delta", "cross", "alibi",
						  "awoke", "drake", "llama", "twerp", "inked", "small", "crazy", "onion"  ],
						[ "obsessing", "gallingly", "deadheads", "ratcheted",
						  "belle", "enter", "sleek", "niece", "serve", "ended", "curse", "lurid",
						  "allot", "clear", "enema", "kneel", "ensue", "erred", "colon", "rural"  ],
						[ "palanquin", "canneries", "hankering", "cakewalks",
						  "aloft", "artsy", "quart", "input", "guava", "speck", "owner", "clean",
						  "about", "entry", "alpha", "titan", "aegis", "knave", "occur", "niece"  ],
						[ "quibblers", "pandering", "deadliest", "caddishly",
						  "outer", "borne", "later", "rebel", "amaze", "fiend", "swami", "basis",
						  "after", "dirge", "tibia", "riled", "scarf", "lease", "sober", "arson"  ],
						[ "unadverse", "jockeying", "sanitizer", "waspiness",
						  "night", "dally", "earls", "sidle", "polka", "swami", "corgi", "twine",
						  "angel", "putty", "rodeo", "steak", "napes", "salsa", "catty", "reign"  ],
						[ "jocularly", "imbecilic", "necessity", "halfpence",
						  "oaken", "under", "alder", "liege", "spike", "leave", "stabs", "swift",
						  "asked", "finer", "dream", "reeve", "easel", "china", "sushi", "alibi"  ],
						[ "unabiding", "abnegates", "rationing", "vacuously",
						  "night", "barge", "deter", "nervy", "tibia", "radii", "paean", "alien",
						  "anger", "untie", "throb", "rhyme", "utter", "lobed", "plaza", "elite"  ],
						[ "backflips", "venomless", "canneries", "eggshells",
						  "avail", "koala", "leash", "pearl", "hyena", "clean", "bower", "alive",
						  "guava", "salsa", "awake", "hello", "ethic", "leese", "brawl", "waits"  ],
						[ "habitancy", "majesties", "magicians", "kilovolts",
						  "agape", "inept", "aster", "chaff", "copra", "radii", "alibi", "grain",
						  "inane", "overt", "tiara", "rifle", "occur", "taped", "aught", "irate"  ],		//40
						[ "talkathon", "saddening", "damnedest", "handballs",
						  "arrow", "knife", "tetra", "ombre", "guava", "risen", "posed", "chaps",
						  "atria", "dowse", "tibia", "ahead", "anger", "leads", "pecan", "slain"  ],
						[ "dairymaid", "washrooms", "kingmaker", "feathered",
						  "anvil", "resin", "myrrh", "inset", "ennui", "doing", "llama", "shame",
						  "elves", "talon", "rasta", "hutch", "emend", "ennui", "lasso", "alarm"  ],
						[ "unbuttons", "filtering", "canonized", "halfmoons",
						  "naive", "usury", "terse", "nadir", "salsa", "tongo", "sushi", "plume",
						  "adieu", "fiery", "radii", "egret", "onset", "nylon", "super", "spurn"  ],
						[ "backslaps", "calamaris", "bagpipers", "sartorial",
						  "avoid", "kinky", "lingo", "pence", "santa", "tramp", "stamp", "prior",
						  "acorn", "today", "ninja", "opera", "reset", "apnea", "sepia", "alibi"  ],
						[ "quintuple", "debutante", "bacterial", "ganglions",
						  "uncut", "noted", "units", "llama", "santa", "tract", "debar", "larva",
						  "ascot", "gated", "irate", "snafu", "inset", "ninja", "delta", "burst"  ],
						[ "negotiate", "genuinely", "obviation", "sacrilege",
						  "easel", "owned", "ideas", "tiara", "throb", "sushi", "beast", "turbo",
						  "arson", "ruled", "erase", "snafu", "lotus", "girds", "baton", "aural"  ],
						[ "queesiest", "unclothed", "backdates", "waferlike",
						  "under", "epoch", "irons", "spike", "karma", "spank", "delta", "brave",
						  "audio", "earth", "onion", "smell", "lakes", "karma", "debut", "leave"  ],
						[ "jukeboxes", "manganese", "echograms", "obsession",
						  "usurp", "every", "octet", "extra", "optic", "cargo", "sugar", "dream",
						  "brute", "empty", "tetra", "twang", "stoic", "otter", "sedan", "guess"  ],
						[ "captivity", "ulcerated", "nailheads", "qualified",
						  "arise", "tinny", "veils", "tutor", "arena", "snail", "evoke", "tuned",
						  "union", "leery", "intel", "surge", "flats", "enema", "extra", "ounce"  ],
						[ "verminous", "ideations", "jauntiest", "eastwards",
						  "error", "melee", "nerve", "uncut", "mocha", "train", "sushi", "atlas",
						  "aural", "terse", "raced", "extra", "admit", "dacha", "swami", "salon"  ],		//50
						[ "nationals", "jumpsuits", "handstand", "canoodles",
						  "apace", "islet", "nasal", "leant", "aloha", "ached", "toast", "yearn",
						  "avail", "overt", "snafu", "litup", "drama", "epoch", "bayou", "adapt"  ],
						[ "ultrarich", "ballparks", "jumpsuits", "nastiness",
						  "loose", "rotor", "rifle", "crops", "adieu", "sleep", "snafu", "meant",
						  "afoot", "their", "flora", "easel", "nears", "swipe", "samba", "aback"  ],
						[ "taquerias", "unclutter", "laborious", "lactating",
						  "amity", "unmet", "relic", "anger", "polka", "canto", "sushi", "adieu",
						  "axiom", "tryst", "login", "coral", "topic", "nylon", "start", "spice"  ],
						[ "marijuana", "genealogy", "verbalise", "absurdist",
						  "aided", "inter", "unlit", "nurse", "phase", "throb", "prowl", "raids",
						  "bidet", "under", "large", "theme", "depot", "stair", "peril", "owing"  ],
						[ "falconers", "debarking", "omissions", "panoplies",
						  "abase", "chest", "nomad", "royal", "totem", "hurts", "khaki", "alien",
						  "adage", "overt", "maybe", "delta", "latch", "eater", "knack", "align"  ],
						[ "parabolas", "laudatory", "mandolins", "pandering",
						  "arise", "alias", "offed", "abode", "media", "amend", "focal", "coven",
						  "alibi", "dress", "flora", "dread", "rumba", "nudge", "facet", "cover"  ],
						[ "obstructs", "mainlands", "tactician", "sailboats",
						  "breed", "titan", "udder", "tales", "tiara", "onset", "colic", "magma",
						  "agent", "laden", "delta", "resin", "outdo", "traps", "comma", "luged"  ],
						[ "imploding", "jellyfish", "occultism", "joyriders",
						  "medal", "lined", "dirge", "night", "cubic", "adieu", "great", "ideas",
						  "olden", "ruled", "ridge", "extol", "dacha", "rabbi", "grief", "evens"  ],
						[ "viciously", "saltiness", "raconteur", "tablefuls",
						  "ingot", "inner", "uncut", "lingo", "tibia", "hello", "abbot", "snafu",
						  "argon", "later", "conga", "trout", "fetch", "label", "arson", "brass"  ],
						[ "illnesses", "abolishes", "glacially", "watchable",
						  "leave", "nanny", "super", "equip", "shell", "ethic", "plaza", "shall",
						  "again", "chewy", "plumb", "repel", "aisle", "leech", "poses", "awake"  ],	//60
						[ "reassures", "networked", "offerings", "wasteland",
						  "erect", "slain", "unfit", "elder", "aloof", "suede", "swami", "among",
						  "arena", "titan", "fudge", "throw", "loads", "noose", "stair", "adore"  ],
						[ "juxtapose", "immigrant", "jellyfish", "harshness",
						  "usual", "these", "peaks", "ships", "twine", "steel", "scarf", "aegis",
						  "acute", "solve", "axiom", "sushi", "notes", "seize", "stair", "argon"  ],
						[ "acclimate", "paginated", "venomless", "navigable",
						  "chime", "limit", "magic", "timer", "chafe", "dingo", "aural", "nouns",
						  "axiom", "inert", "gamma", "corgi", "arced", "learn", "apnea", "reuse"  ],
						[ "jointless", "yearbooks", "networked", "radiators",
						  "olden", "nadir", "locus", "slurp", "addle", "arrow", "deter", "slate",
						  "added", "inner", "chute", "super", "tiara", "rider", "disco", "thank"  ],
						[ "navigator", "glaringly", "backflips", "balconies",
						  "aware", "idler", "ached", "optic", "sauna", "dreck", "bagel", "scalp",
						  "avail", "cheer", "hotel", "decor", "nosed", "elude", "basin", "grail"  ],
						[ "fictional", "genotypes", "panoplies", "feistiest",
						  "inter", "tenet", "offal", "amass", "plaza", "lotto", "towel", "slake",
						  "eaten", "strut", "frame", "lasso", "impel", "shaft", "tasty", "weave"  ],
						[ "immunized", "teardowns", "washboard", "acrobatic",
						  "mitre", "undue", "ideal", "ebony", "villa", "lurch", "hello", "diver",
						  "cited", "obese", "erode", "layer", "anvil", "idler", "hydro", "liven"  ],
						[ "decertify", "dealmaker", "baboonish", "verbalise",
						  "evict", "eaten", "totem", "frond", "aorta", "tempo", "cabin", "chaps",
						  "edict", "baton", "those", "modal", "leant", "strum", "cocoa", "blare"  ],
						[ "feedstock", "parakeets", "lacerated", "immorally",
						  "erase", "doyen", "tiara", "copse", "aorta", "suede", "china", "aside",
						  "meaty", "ocean", "alpha", "arena", "amass", "large", "crane", "idiot"  ],
						[ "handlebar", "vegetable", "whichever", "deadliest",
						  "awful", "dunce", "evict", "amaze", "swish", "ethic", "phase", "slave",
						  "elfin", "delve", "image", "there", "issue", "swish", "pasta", "avail"  ],	//70
						[ "cannoneer", "rearrests", "sanitizes", "jumpsuits",
						  "ample", "nurse", "nests", "exile", "drama", "ennui", "corgi", "azure",
						  "upper", "piece", "suite", "spear", "undue", "train", "craze", "roust"  ],
						[ "ejections", "uncoupled", "eccentric", "handicaps",
						  "jaded", "crone", "impel", "needs", "optic", "tonne", "strut", "radii",
						  "audio", "dodge", "paean", "lasso", "clout", "piton", "scrap", "ridge"  ],
						[ "absorbing", "malleable", "dampening", "handballs",
						  "bloat", "owner", "biker", "nippy", "larva", "whelp", "vegan", "deign",
						  "adorn", "deter", "kappa", "royal", "aglow", "large", "vodka", "grill"  ],
						[ "rebranded", "facecloth", "taekwondo", "harmonist",
						  "event", "roach", "nasal", "elude", "sauna", "speck", "intro", "paced",
						  "arena", "match", "scuba", "liege", "nests", "spume", "impel", "tacit"  ],
						[ "hardships", "vestibule", "imbeciles", "happening",
						  "acorn", "dwell", "haste", "prise", "opium", "nooks", "swami", "revue",
						  "alone", "penal", "swipe", "event", "sieve", "naive", "scrub", "anvil"  ]
];  //75
