
var Solutions500 = [ [ "uplifting", "unmatched", "shortfall", "evidenced",
							  "prior", "image", "totem", "noted", "touch", "sheer", "chaff", "brawl",
							  "voila", "dirge", "titan", "media", "notes", "exude", "cubic", "amaze"  ],
							[ "vaccinate", "apportion", "milestone", "webcaster",
							  "aspen", "cello", "noted", "trout", "alibi", "sieve", "uncut", "sheen",
							  "expel", "canto", "troop", "ditto", "snaps", "elite", "upset", "credo"  ],
							[ "redolence", "perdition", "implement", "melodious",
							  "elect", "onset", "evoke", "clear", "opium", "shell", "scrum", "eaten",
							  "evens", "octet", "obese", "erred", "irons", "unite", "sweat", "retro"  ],
							[ "collision", "optimizes", "lamplight", "sacrifice",
							  "ombre", "lathe", "super", "ogled", "manna", "runup", "cacti", "reach",
							  "abbot", "reeve", "polyp", "radii", "femur", "canon", "corgi", "chafe"  ],
							[ "taphouses", "terahertz", "orienting", "cubbyhole",
							  "amber", "honey", "umbra", "eaten", "udder", "since", "leapt", "argon",
							  "urban", "barmy", "bathe", "apnea", "hauls", "laden", "lease", "angst"  ],
							[ "injustice", "feathered", "mechanism", "flattered",
							  "nines", "ulnas", "tatty", "cobra", "globe", "reach", "align", "poses",
							  "linen", "tests", "table", "yeast", "eager", "ebola", "ample", "issue"  ],
							[ "whimpered", "cheerless", "megahertz", "ceaseless",
							  "horde", "marry", "expel", "equip", "sauce", "omega", "booze", "stoat",
							  "error", "seedy", "pouch", "lapse", "lasso", "saute", "basil", "oboes"  ],
							[ "blackbird", "handholds", "finalizes",  "midstream",
							  "lucre", "caret", "burst", "remix", "corgi", "panda", "cacti", "loose",
							  "incur", "spent", "rumba", "taxed", "recap", "apron", "cello", "cloud"  ],
							[ "deflected", "blemished", "grimoires", "gardeners",
							  "ebola", "learn", "carom", "erred", "amber", "strum", "cacti", "aisle",
							  "aroma", "drain", "rural", "madam", "neaps", "rebar", "crass", "caste"  ],
							[ "provident", "blundered", "tolerated", "laminated",
							  "rhino", "vines", "debar", "nutty", "gusto", "there", "panda", "reeve",
							  "align", "irons", "betel", "rayon", "aught", "ensue", "parse", "niece"  ],		//510
							[ "sunflower", "padlocked", "weeknight", "peregrine",
							  "utter", "foamy", "ought", "exact", "large", "check", "cacti", "booth",
							  "extra", "early", "guava", "total", "relic", "nurse", "cubic", "chore"  ],
							[ "varnishes", "novelties", "parasitic", "abhorrent",
							  "adorn", "nadir", "spool", "extra", "libra", "cobra", "cacti", "ennui",
							  "brood", "owner", "outdo", "leave", "relic", "nabob", "chest", "canoe"  ],
							[ "reappoint", "beginning", "reprimand", "hooligans",
							  "evoke", "party", "otter", "nabob", "orate", "poser", "album", "grown",
							  "odour", "leery", "table", "rabbi", "group", "nears", "argon", "brown"  ],
							[ "washrooms", "footprint", "velodrome", "venerated",
							  "augur", "harry", "ovate", "maize", "drape", "polio", "caber", "realm",
							  "eager", "early", "amino", "event", "addup", "email", "carer", "brain"  ],
							[ "geriatric", "nanorobot", "militants", "gathering",
							  "exact", "intel", "topic", "issue", "cacti", "sushi", "dacha", "spent",
							  "apart", "hotel", "pasta", "credo", "rocks", "nicks", "disco", "credo"  ],
							[ "venerable", "mentoring", "lethargic", "variously",
							  "eyrie", "enact", "award", "login", "binge", "ninth", "upper", "cacti",
							  "aorta", "inept", "angle", "donut", "urban", "linen", "ulcer", "pecan"  ],
							[ "generated", "nonkosher", "deflected", "parchment",
							  "eagle", "eject", "angst", "erase", "lathe", "spoil", "logic", "slope",
							  "algae", "cheat", "guano", "tweak", "miles", "nitro", "loses", "grope"  ],
							[ "outdoorsy", "spymaster", "precursor", "drugstore",
							  "urged", "dolly", "optic", "shape", "paper", "conic", "wager", "torso",
							  "regal", "giddy", "tramp", "cream", "topic", "ripen", "watts", "gorse"  ],
							[ "enveloped", "energetic", "gangplank", "batteries",
							  "nabob", "early", "otter", "email", "apnea", "thing", "nasal", "brawn",
							  "amber", "tubby", "train", "ruler", "roast", "ennui", "noble", "swami"  ],
							[ "narrators", "direction", "homegrown", "schooners",
							  "agile", "reeve", "tweet", "rants", "rodeo", "surge", "alter", "elbow",
							  "chide", "obese", "ennui", "taste", "nerds", "rider", "agent", "taboo"  ],		//520
							[ "witnessed", "adversely", "foolproof", "bountiful",
							  "incur", "nurse", "snack", "extra", "outdo", "steal", "piper", "audio",
							  "occur", "nerve", "acted", "knave", "irons", "untie", "peaks", "pedal"  ],
							[ "withdrawn", "dentistry", "despaired", "poisonous",
							  "ideal", "heavy", "robed", "world", "metre", "scalp", "cacti", "leave",
							  "omega", "silty", "borne", "didit", "names", "ultra", "cells", "chair"  ],
							[ "policeman", "tribesmen", "drainpipe", "passports",
							  "ogler", "issue", "exact", "ardor", "hiker", "ennui", "scrap", "frump",
							  "atlas", "surge", "adder", "throb", "ochre", "token", "sifts", "route"  ],
							[ "sideburns", "malaprops", "hermitage", "predicate",
							  "ingot", "evens", "uncut", "nabob", "dirge", "swarm", "facet", "wring",
							  "rogue", "dates", "cobra", "tibia", "codes", "terra", "fewer", "crisp"  ],
							[ "dachshund", "remembers", "firsthand", "carpenter",
							  "anger", "hinge", "heart", "nabob", "khaki", "dress", "torch", "urban",
							  "argon", "purge", "amble", "table", "naked", "elate", "thumb", "rebar"  ],
							[ "spotlight", "depressed", "mortality", "earpieces",
							  "piton", "tasty", "ideal", "hurts", "tango", "print", "canal", "uncut",
							  "antes", "pansy", "eyrie", "laser", "eatup", "ennui", "chums", "niche"  ],
							[ "messaging", "bathwater", "radiology", "permeated",
							  "enter", "stain", "grant", "ninja", "tetra", "corgi", "until", "thong",
							  "extra", "moron", "apnea", "trash", "attic", "enter", "ultra", "trove"  ],
							[ "terahertz", "starlight", "scrapings", "vouchsafe",
							  "exits", "aimed", "eaves", "tilde", "tunic", "salsa", "corgi", "clung",
							  "opium", "cased", "valet", "swear", "sites", "final", "cacti", "rough"  ],
							[ "acridness", "hijackers", "telegraph", "demarcate",
							  "crude", "inlet", "nurse", "sidle", "apace", "title", "baser", "tramp",
							  "equal", "alert", "radii", "enema", "chart", "toast", "batik", "stair"  ],
							[ "avuncular", "ransacked", "kilowatts", "highlands",
							  "venom", "nicer", "uncut", "admit", "alibi", "metro", "magma", "glint",
							  "ionic", "humor", "comma", "totes", "alarm", "drift", "magic", "glide"  ],		//530
							[ "heartless", "telegraph", "adjoining", "grievance",
							  "elder", "raise", "linen", "seize", "broad", "radio", "churn", "dozen",
							  "radii", "eerie", "noise", "niece", "amber", "chord", "cider", "unzip"  ],
							[ "belonging", "waterline", "beginners", "heartless",
							  "eaten", "ogres", "gloat", "needs", "baste", "alibi", "plain", "riser",
							  "enter", "rings", "opera", "taste", "libra", "sushi", "peril", "arson"  ],
							[ "brashness", "education", "teasingly", "gentlemen",
							  "recce", "splay", "night", "sleep", "stole", "evens", "sedan", "until",
							  "excel", "teeny", "greed", "topic", "ensue", "evoke", "spurt", "ditto"  ],
							[ "holdovers", "pendulums", "dehydrate", "jukeboxes",
							  "ovate", "dress", "verge", "raved", "there", "dryly", "visor", "croft",
							  "usage", "evens", "revue", "ended", "opted", "elegy", "vocal", "storm"  ],
							[ "latchkeys", "heiresses", "newsprint", "watershed",
							  "amour", "caged", "krill", "yearn", "alone", "meets", "wiper", "cairn",
							  "among", "erred", "inane", "loner", "spasm", "elope", "wicks", "prize"  ],
							[ "mincemeat", "stuttered", "farseeing", "timelines",
							  "igloo", "cutie", "mimic", "adieu", "pasta", "treks", "usage", "drain",
							  "inlet", "erode", "moist", "crust", "input", "ensue", "undue", "agate"  ],
							[ "landfills", "greenbelt", "contained", "character",
							  "apron", "dandy", "intel", "leper", "rhino", "sleet", "cacti", "unite",
							  "heron", "rangy", "taper", "large", "corps", "elite", "crumb", "chill"  ],
							[ "graveyard", "gentlemen", "haplotype", "barhopped",
							  "roars", "venue", "years", "riper", "pasta", "spell", "fault", "addup",
							  "again", "haste", "ample", "strut", "popes", "ensue", "flame", "undue"  ],
							[ "vacancies", "sevenfold", "worthless", "flowerpot",
							  "argon", "annoy", "crows", "evade", "tango", "swept", "petal", "omits",
							  "logon", "windy", "ovate", "sieve", "rites", "ounce", "proof", "trial"  ],
							[ "princedom", "entranced", "abolished", "withdraws",
							  "raged", "nitre", "erase", "onset", "scrub", "smell", "tyres", "liege",
							  "ingot", "hedge", "arson", "enter", "rests", "worse", "talon", "reeve"  ],		//540
							[ "bolstered", "unelected", "bicyclist", "nightcaps",
							  "obeys", "salve", "erase", "ethic", "alibi", "mushy", "brawl", "sorts",
							  "ideal", "haste", "ashen", "excel", "charm", "priss", "basic", "aerie"  ],
							[ "disbelief", "radiating", "recreates", "kerchiefs",
							  "inter", "blast", "lover", "ended", "grave", "taker", "polka", "vogue",
							  "extra", "carat", "vodka", "radii", "ingot", "frank", "pivot", "login"  ],
							[ "nominally", "tightened", "emanation", "weaseling",
							  "ocean", "inter", "asses", "llama", "steam", "risen", "adopt", "bravo",
							  "erect", "saner", "swami", "stash", "loser", "needs", "amble", "orate"  ],
							[ "finagling", "undeleted", "discarded", "osteopath",
							  "irate", "artsy", "lords", "nomen", "swami", "relic", "power", "range",
							  "scant", "enemy", "ramen", "sense", "poser", "trail", "puree", "wince"  ],
							[ "fearfully", "deadlocks", "medicates", "nominates",
							  "enact", "royal", "ulnas", "lycra", "loose", "sushi", "copra", "crave",
							  "ovary", "intel", "niche", "stand", "axles", "ebons", "cacao", "prank"  ],
							[ "canonical", "microcosm", "companion", "violinist",
							  "augur", "optic", "irate", "apish", "rhino", "eatup", "argon", "torso",
							  "ingot", "lyric", "alibi", "ether", "nerve", "skirt", "antic", "gores"  ],
							[ "estimated", "partaking", "latencies", "disengage",
							  "shake", "inept", "attic", "embed", "umbra", "these", "cubic", "amaze",
							  "irate", "eject", "tibia", "cadet", "grunt", "gable", "crack", "brawn"  ],
							[ "heretical", "jessamine", "narration", "scrounged",
							  "embed", "error", "infer", "album", "manna", "drier", "great", "outdo",
							  "caber", "order", "fable", "ramps", "nomad", "ennui", "gloom", "eaten"  ],
							[ "dictation", "conducted", "sabotages", "balancing",
							  "inane", "tread", "teams", "organ", "dogma", "ditto", "mocha", "dirge",
							  "aware", "ahead", "anglo", "synod", "coded", "night", "medic", "curse"  ],
							[ "sociology", "immediate", "copyright", "sugarcoat",
							  "ombre", "inapt", "lusts", "groan", "anglo", "holly", "corgi", "couch",
							  "umbra", "agent", "storm", "singe", "coach", "angel", "cacti", "roust"  ],		//550
							[ "selection", "osteopath", "rephrased", "steadfast",
							  "easel", "evens", "tiger", "onion", "exile", "teeth", "comma", "amaze",
							  "taste", "atlas", "grits", "rinse", "fleet", "slime", "clasp", "meant"  ],
							[ "pacemaker", "starlight", "honeymoon", "canticles",
							  "abate", "every", "aloud", "event", "pluto", "delve", "cream", "cargo",
							  "agape", "teeny", "overt", "deter", "coped", "equal", "cacti", "earth"  ],
							[ "increases", "collision", "underfund", "unchanged",
							  "niner", "reach", "artsy", "erred", "eaten", "slate", "pilaf", "nomen",
							  "ninja", "harsh", "torso", "yodel", "needs", "extra", "pants", "limbo"  ],
							[ "royalties", "valiantly", "disinfect", "sepulchre",
							  "outed", "apace", "trees", "evens", "radii", "ennui", "bluff", "attic",
							  "extra", "undue", "enema", "sushi", "curse", "radon", "brawn", "until"  ],
							[ "recording", "economist", "wearingly", "mortified",
							  "erect", "opals", "dimly", "ninja", "wedge", "rarer", "shorn", "aural",
							  "opera", "totes", "manic", "yearn", "fewer", "elder", "spasm", "ogres"  ],
							[ "skippered", "headlines", "penthouse", "unelected",
							  "known", "plead", "edict", "elate", "exile", "slept", "ratio", "dress",
							  "noose", "lined", "irate", "tread", "chess", "elite", "radii", "there"  ],
							[ "compactor", "legendary", "champagne", "secretion",
							  "omens", "patty", "cutie", "outer", "teach", "dream", "delta", "eaten",
							  "event", "raspy", "title", "eerie", "toted", "ovate", "dread", "later"  ],
							[ "posterior", "lettering", "defrosted", "catfished",
							  "orate", "tides", "retro", "ovens", "agree", "enter", "class", "goose",
							  "award", "frees", "these", "onset", "slake", "egret", "cigar", "acorn"  ],
							[ "polarized", "dromedary", "peasantry", "spacewalk",
							  "odour", "alloy", "inert", "eight", "eerie", "teens", "sworn", "otter",
							  "prowl", "curly", "eager", "totem", "wrest", "large", "scold", "outer"  ],
							[ "flavoured", "detracted", "chastised", "pressgang",
							  "label", "valid", "unwed", "exert", "awash", "noses", "alibi", "trade",
							  "rebel", "salad", "where", "deter", "grain", "nears", "attic", "irate"  ],		//560
							[ "intrigued", "paleology", "undertone", "lampposts",
							  "nails", "rails", "gauge", "ember", "drawn", "niece", "uncut", "train",
							  "alibi", "poses", "umbra", "eyrie", "olden", "trade", "until", "clang"  ],
							[ "vivacious", "footrests", "maladroit", "washables",
							  "ideal", "addle", "icing", "untie", "arena", "extra", "cedar", "chili",
							  "amend", "halve", "intro", "great", "blame", "erect", "cache", "drift"  ],
							[ "stratagem", "segregate", "matchbook", "backbiter",
							  "tripe", "atoll", "amber", "equip", "pasta", "lilac", "throb", "anglo",
							  "amino", "knell", "brute", "riper", "impel", "easel", "twang", "right"  ],
							[ "maladroit", "embodying", "misfiring", "paddocked",
							  "asset", "amend", "rider", "inert", "alibi", "sheaf", "solar", "drain",
							  "aisle", "doted", "dream", "ratio", "crass", "elite", "soddy", "learn"  ],
							[ "doctorate", "reasoning", "snowdrift", "paintball",
							  "odour", "theme", "radon", "twist", "aspen", "endow", "rotor", "dwarf",
							  "awoke", "nerve", "drive", "notes", "blaze", "loped", "radon", "train"  ],
							[ "handicaps", "unimpeded", "champagne", "spaghetti",
							  "algae", "dance", "champ", "pasta", "gulch", "steam", "cobra", "acorn",
							  "pagan", "geese", "arson", "psalm", "edges", "tilde", "cease", "booze"  ],
							[ "cattiness", "mainlines", "patterned", "inelegant",
							  "axiom", "tryst", "noted", "scram", "comma", "onset", "sugar", "snake",
							  "noisy", "limit", "terra", "demon", "gecko", "names", "sushi", "grade"  ],
							[ "thirtieth", "giveaways", "throttles", "nightlife",
							  "heels", "raspy", "inert", "toner", "myrrh", "retro", "egret", "drone",
							  "ideas", "hasty", "ennui", "terse", "lemur", "first", "endow", "roomy"  ],
							[ "resultant", "reinstate", "enshrined", "textbooks",
							  "enter", "usage", "tuned", "nitro", "sworn", "tenth", "swami", "gauze",
							  "extra", "three", "nitre", "drown", "onset", "known", "sight", "adult"  ],
							[ "terseness", "reformist", "flimsiest", "scaffolds",
							  "exert", "stood", "nasal", "spurt", "towel", "scrum", "sushi", "reads",
							  "credo", "fated", "sauce", "lotto", "oaths", "dower", "strum", "snaps"  ],		//570
							[ "keepsakes", "cathartic", "propriety", "kilohertz",
							  "evict", "petal", "anvil", "exile", "aster", "tramp", "sushi", "graft",
							  "idiot", "octal", "voila", "leech", "exact", "tetra", "sugar", "swami"  ],
							[ "escalator", "parentage", "trimmings", "imperfect",
							  "sauna", "annul", "above", "omens", "rider", "dream", "alibi", "bring",
							  "mourn", "email", "opera", "ensue", "fared", "cadge", "ambit", "icing"  ],
							[ "layabouts", "newsreels", "berserker", "testament",
							  "among", "abhor", "ovals", "trial", "terse", "roses", "inter", "awoke",
							  "epoch", "tiger", "alive", "salts", "meter", "nerds", "irate", "troll"  ],
							[ "teenagers", "recondite", "parachute", "marauding",
							  "ember", "nomen", "gamer", "round", "pasta", "salsa", "awash", "roast",
							  "album", "apron", "mouse", "radio", "dupes", "nasal", "acrid", "adapt"  ],
							[ "likeliest", "beginning", "absconder", "tolerated",
							  "incur", "earls", "inter", "scald", "rehab", "lyric", "widen", "moose",
							  "occur", "earns", "trade", "radii", "aural", "ether", "woman", "drown"  ],
							[ "hypnotist", "backdated", "emotional", "craftsman",
							  "yearn", "nutty", "totes", "surge", "serum", "islet", "cargo", "panda",
							  "roast", "fancy", "terra", "sleek", "sushi", "aural", "copra", "rinse"  ],
							[ "semesters", "ceaseless", "disbarred", "partygoer",
							  "elope", "enact", "tired", "route", "radii", "shrub", "radar", "gripe",
							  "aroma", "tweet", "rouge", "dress", "gores", "eider", "regal", "dries"  ],
							[ "parameter", "greetings", "medicinal", "occipital",
							  "aunts", "allot", "erect", "ethos", "elite", "sushi", "chili", "china",
							  "canal", "inset", "ether", "taste", "ideas", "amiss", "cacti", "icing"  ],
							[ "shambolic", "larcenies", "matriarch", "fulfilled",
							  "humor", "metal", "odour", "ideal", "aorta", "ardor", "mafia", "stoic",
							  "unmet", "feral", "opera", "relic", "llama", "erred", "mason", "froze"  ],
							[ "barnyards", "southeast", "frustrate", "addressed",
							  "acrid", "needs", "above", "deter", "aster", "tires", "sonar", "giant",
							  "dirge", "rides", "outdo", "egret", "smart", "enter", "segue", "nears"  ],		//580
							[ "champagne", "voltmeter", "panellist", "carnelian",
							  "humid", "modes", "abort", "nitre", "gamma", "ledge", "level", "rings",
							  "aimed", "nodes", "outdo", "theft", "legal", "armed", "large", "venue"  ],
							[ "abolished", "defeatist", "earthwork", "undercard",
							  "berth", "laser", "shrug", "exile", "extra", "midst", "widow", "rotor",
							  "nerds", "ether", "raise", "geese", "cream", "rated", "worst", "dates"  ],
							[ "overdress", "orienting", "performed", "indicting",
							  "vitro", "risky", "rapid", "sewer", "smite", "shelf", "rotor", "brace",
							  "notes", "ivory", "power", "dirge", "tests", "naive", "robot", "train"  ],
							[ "haciendas", "undercard", "imbalance", "casserole",
							  "amaze", "ideal", "nitro", "adage", "album", "tiara", "sauna", "optic",
							  "apace", "spell", "train", "obese", "roast", "libra", "stoic", "utter"  ],
							[ "underhand", "momentary", "decagonal", "habitable",
							  "nails", "eagle", "hunch", "notes", "glove", "opera", "cameo", "manna",
							  "axing", "issue", "nitro", "haste", "anglo", "loose", "comet", "manor"  ],
							[ "ingenious", "unscrewed", "ingestion", "racehorse",
							  "nails", "ebony", "inset", "union", "sworn", "terse", "feast", "disco",
							  "amino", "essay", "scion", "tunic", "onset", "scour", "fudge", "aisle"  ],
							[ "paintball", "somewhere", "frugality", "boathouse",
							  "awful", "nadir", "batik", "libra", "stair", "thing", "avail", "afoot",
							  "offed", "tiler", "taboo", "knave", "onset", "swami", "awash", "amour"  ],
							[ "unhitched", "cybercafe", "snickered", "decorates",
							  "noses", "inert", "cared", "email", "churn", "topic", "issue", "irate",
							  "ensue", "onset", "ready", "delve", "ascot", "equip", "iliac", "staff"  ],
							[ "secretary", "adversary", "climactic", "prominent",
							  "enter", "roomy", "timed", "ripen", "model", "dream", "relic", "sushi",
							  "ratio", "murky", "moped", "dense", "nomad", "nudge", "ruses", "laser"  ],
							[ "cuneiform", "salivated", "starboard", "narcotics",
							  "udder", "elect", "fiver", "riled", "leant", "roger", "cargo", "prior",
							  "addle", "carat", "villa", "radii", "tiler", "clang", "copra", "raise"  ],		//590
							[ "jetliners", "corpulent", "unrivaled", "staunchly",
							  "elect", "lease", "napes", "roast", "pagan", "radii", "drama", "chore",
							  "theta", "untie", "piano", "setup", "caper", "luged", "decal", "acorn"  ],
							[ "incubator", "destitute", "malformed", "nonmember",
							  "needy", "utter", "adage", "odour", "llama", "shelf", "flair", "route",
							  "overt", "mayor", "abode", "egret", "miles", "evade", "first", "adult"  ]
];  //592
