
var Solutions300 = [ [ "necklines", "glassware", "blackmail", "deepening",
							  "eight", "kneel", "input", "ebola", "total", "stoic", "alarm", "radii",
							  "eagle", "petal", "prowl", "toads", "notes", "nitro", "arrow", "adder"  ],
							[ "kindliest", "regarding", "dictation", "eldercare",
							  "inter", "dirty", "impel", "skier", "corgi", "inlet", "front", "audio",
							  "later", "early", "pride", "larva", "cacti", "rural", "fraud", "olden"  ],
							[ "profusion", "absentees", "jettisons", "nurseries",
							  "radon", "feeds", "sects", "onion", "trade", "smelt", "irons", "groin",
							  "undue", "sends", "climb", "sense", "rites", "evade", "ingot", "ozone"  ],
							[ "hatchback", "doddering", "satirized", "masochist",
							  "apple", "chess", "bigot", "clasp", "viola", "sushi", "swami", "abide",
							  "ample", "ovens", "guano", "taped", "hives", "spots", "stair", "alien"  ],
							[ "methadone", "ventilate", "carousers", "jailbirds",
							  "eaten", "heron", "digit", "noise", "ninja", "credo", "totes", "augur",
							  "alter", "linen", "gripe", "treat", "ionic", "dunce", "trawl", "tight"  ],
							[ "espionage", "bloodline", "dairymaid", "scoreless",
							  "stump", "irked", "nests", "growl", "sigma", "sneer", "swarm", "emoji",
							  "clunk", "roped", "spool", "salvo", "loses", "segue", "shell", "adorn"  ],
							[ "nonprofit", "destitute", "saxophone", "degrading",
							  "optic", "phase", "ovals", "impel", "magma", "ditto", "march", "argon",
							  "extra", "recce", "ample", "split", "domed", "night", "meant", "right"  ],
							[ "legalizes", "uncloaked", "embryonic", "sartorial",
							  "edify", "arise", "inlet", "exact", "cream", "rotor", "canto", "cacti",
							  "alibi", "thyme", "learn", "total", "racer", "alert", "cocoa", "niche"  ],
							[ "necklines", "haymakers", "rhapsodic", "pictogram",
							  "elbow", "knell", "infer", "ebola", "myrrh", "tramp", "salvo", "ennui",
							  "imbue", "towel", "flora", "realm", "gamut", "aorta", "sleek", "liner"  ],
							[ "pedigrees", "scoreless", "garnetted", "relevance",
							  "equip", "intel", "ruler", "edged", "omega", "groan", "beret", "slate",
							  "exult", "expel", "logic", "radar", "among", "credo", "basil", "reaps"  ],		//310
							[ "absorbent", "steampunk", "telemetry", "introduce",
							  "bulky", "ounce", "brash", "niece", "gorge", "atone", "cable", "amour",
							  "nylon", "rhyme", "alert", "hyena", "dogma", "cargo", "cramp", "brown"  ],
							[ "armadillo", "defendant", "beckoning", "broadcast",
							  "rebel", "arrow", "ideal", "leapt", "grime", "dreck", "clown", "stern",
							  "rebar", "aglow", "evade", "lithe", "caged", "seize", "cased", "ocean"  ],
							[ "unashamed", "president", "unopposed", "maximized",
							  "napes", "scare", "alias", "elfin", "stern", "tramp", "pluto", "slime",
							  "alpha", "issue", "infer", "sinus", "inset", "enema", "posed", "union"  ],
							[ "readjusts", "inception", "connector", "cantering",
							  "ember", "dimes", "ulcer", "tally", "patio", "doyen", "tunic", "metro",
							  "album", "tires", "colon", "rhyme", "roped", "nutty", "tempt", "nitro"  ],
							[ "interfere", "yodelling", "mothballs", "spineless",
							  "noted", "elope", "farce", "rodeo", "polio", "sloth", "media", "trial",
							  "patio", "nudge", "radio", "evoke", "lopes", "salvo", "motel", "deign"  ],
							[ "waywardly", "generated", "embellish", "maltreats",
							  "allay", "wowed", "relic", "liven", "rearm", "stage", "creel", "coals",
							  "aglow", "toyed", "levee", "canoe", "earls", "tiara", "cocoa", "erase"  ],
							[ "rebooting", "takeaways", "mantissas", "witticism",
							  "eject", "often", "trust", "notes", "arena", "first", "aegis", "llama",
							  "inert", "titan", "ultra", "taste", "chaff", "steer", "allow", "gravy"  ],
							[ "scuppered", "defeating", "bigheaded", "whirligig",
							  "clung", "paste", "ember", "exile", "swami", "teeth", "salsa", "lodge",
							  "hauls", "rogue", "bride", "reeve", "inset", "inane", "splat", "laden"  ],
							[ "marvelled", "celebrity", "shambolic", "prescient",
							  "anvil", "virgo", "loses", "elope", "catch", "scrum", "piano", "sushi",
							  "rover", "salvo", "stone", "sieve", "incas", "noter", "poser", "asset"  ],
							[ "rebutting", "carpentry", "headbands", "dedicated",
							  "eject", "until", "terse", "named", "stale", "trend", "aroma", "owned",
							  "exert", "intel", "rumba", "endup", "asset", "erase", "acorn", "owner"  ],		//320
							[ "deafening", "telltales", "carcasses", "absurdist",
							  "endow", "fused", "needy", "nosed", "aloha", "attic", "coals", "copse",
							  "bides", "unwed", "ensue", "yodel", "drama", "sport", "cocoa", "ample"  ],
							[ "castanets", "fathering", "wickedest", "festivity",
							  "adage", "theft", "nukes", "turbo", "swami", "sleek", "caged", "dross",
							  "erase", "tweet", "karma", "slosh", "vases", "trace", "cedar", "groin"  ],
							[ "joysticks", "eyelashes", "nationals", "semblance",
							  "often", "stray", "inlay", "kiosk", "aorta", "khaki", "argon", "libel",
							  "enter", "bendy", "loony", "yokel", "aback", "circa", "atlas", "gable"  ],
							[ "uninstall", "cellulose", "downsized", "lubricate",
							  "nicks", "needs", "times", "lathe", "lingo", "nylon", "ennui", "anode",
							  "uncle", "roses", "matte", "spell", "colon", "tonal", "email", "nooks"  ],
							[ "eightieth", "leveraged", "estranged", "unwelcome",
							  "inlet", "honey", "igloo", "train", "toads", "deter", "mason", "fable",
							  "nylon", "entry", "lease", "ounce", "cited", "meant", "mafia", "sabre"  ],
							[ "filmmaker", "panellist", "hourglass", "desecrate",
							  "image", "musty", "amend", "eaten", "cargo", "stair", "coral", "elves",
							  "exams", "every", "extra", "dunce", "races", "terra", "creel", "raves"  ],
							[ "fireproof", "generated", "begrudged", "hermitage",
							  "inert", "elate", "robin", "odour", "where", "liner", "mined", "force",
							  "enema", "matte", "broke", "nerve", "towel", "green", "mafia", "nerve"  ],
							[ "suggested", "halfpenny", "enjoyment", "atrophied",
							  "unite", "green", "scald", "enema", "reign", "disco", "modem", "drain",
							  "trite", "ocean", "arena", "dwarf", "hired", "exits", "midge", "drawn"  ],
							[ "discovery", "leviathan", "simpleton", "socialist",
							  "inert", "crawl", "vicar", "rated", "swami", "strop", "aisle", "banjo",
							  "omega", "intel", "cutie", "radii", "loses", "stair", "ambit", "santa"  ],
							[ "margarine", "seascapes", "lecturers", "ensconced",
							  "abort", "glean", "rents", "nicer", "dance", "saint", "tamer", "rider",
							  "noone", "cutin", "niche", "sorts", "nodes", "ennui", "terra", "midge"  ],		//330
							[ "uninvited", "seahorses", "unimpeded", "undersold",
							  "noise", "nasty", "inert", "ebola", "aspen", "gleam", "parse", "poise",
							  "nails", "elegy", "elope", "teach", "slang", "lapse", "piper", "raise"  ],
							[ "verbosity", "panhandle", "yachtsman", "vassalage",
							  "ether", "bendy", "scowl", "there", "tiara", "reach", "sects", "drama",
							  "ashen", "sorry", "opera", "leech", "later", "guava", "sedan", "crawl"  ],
							[ "unlimited", "pigmented", "namesakes", "magnified",
							  "nudge", "ivory", "inked", "elate", "larva", "obese", "polka", "genre",
							  "audio", "needy", "khaki", "dream", "folio", "eerie", "pagan", "lance"  ],
							[ "raspberry", "tantalise", "malaprops", "whackiest",
							  "abase", "potty", "expat", "rarer", "terra", "rumba", "lever", "getup",
							  "heart", "chewy", "parka", "tarot", "inter", "serum", "legal", "votes"  ],
							[ "cabdriver", "newsprint", "lifelines", "autopilot",
							  "argue", "didit", "infer", "erred", "ennui", "there", "swami", "borne",
							  "urged", "overt", "farce", "rides", "inert", "ounce", "sober", "apron"  ],
							[ "joysticks", "barracuda", "vacancies", "lunchtime",
							  "oddly", "spent", "irked", "khaki", "ultra", "pasta", "tonic", "paste",
							  "undue", "crypt", "koala", "drier", "thump", "mites", "topic", "nosed"  ],
							[ "insinuate", "carbuncle", "deflation", "masochist",
							  "noone", "inert", "ulcer", "torch", "ounce", "spell", "craft", "banjo",
							  "alone", "overt", "circa", "rehab", "hoops", "singe", "cabin", "annul"  ],
							[ "observing", "sassiness", "adventure", "enamoured",
							  "bandy", "ensue", "valet", "nicer", "fetid", "trade", "cleft", "never",
							  "nines", "maybe", "lycra", "tyres", "unfit", "extra", "canon", "elves"  ],
							[ "refectory", "hierarchy", "aggrieved", "overrated",
							  "enter", "error", "tests", "roast", "bring", "their", "midge", "latte",
							  "voter", "rarer", "swami", "satyr", "ambit", "elide", "molar", "ditch"  ],
							[ "statement", "replenish", "daredevil", "federally",
							  "trait", "tutor", "mined", "nurse", "drama", "dance", "peeve", "corgi",
							  "exalt", "enter", "nerve", "dwell", "aided", "learn", "pecan", "earls"  ],		//340
							[ "mentality", "mechanism", "embodying", "revolting",
							  "ended", "taper", "login", "their", "dream", "lasso", "seedy", "reign",
							  "endup", "order", "geese", "north", "tidal", "needs", "sarin", "emits"  ],
							[ "opposites", "adversely", "nonlinear", "barbecued",
							  "posed", "oaths", "inlet", "earns", "lingo", "axial", "spawn", "dogma",
							  "asset", "bides", "lurid", "taste", "cilia", "ennui", "sides", "angel"  ],
							[ "hamstrung", "indolence", "toothpick", "bacterium",
							  "anode", "scant", "raven", "night", "cacao", "exert", "cramp", "antic",
							  "aroma", "theft", "vegan", "nitro", "recce", "uncle", "crave", "attic"  ],
							[ "kilobytes", "graduated", "vacancies", "newsbreak",
							  "idiom", "opera", "yield", "earls", "drama", "santa", "manic", "noise",
							  "elite", "samba", "error", "dosed", "rides", "again", "mania", "naive"  ],
							[ "captained", "memorable", "nastiness", "nebulizes",
							  "abort", "taste", "idler", "exult", "ebola", "spent", "train", "bonus",
							  "ebons", "untie", "louse", "retro", "ideas", "elope", "tibia", "annul"  ],
							[ "leakproof", "economist", "tollbooth", "statement",
							  "error", "knave", "racer", "owner", "patio", "shoal", "photo", "inset",
							  "terra", "three", "cynic", "rerun", "mopes", "nitro", "prism", "oasis"  ],
							[ "jackaroos", "hypnotist", "ensembles", "omissible",
							  "aspen", "knead", "rigor", "ovals", "logon", "terse", "redub", "shire",
							  "maple", "synod", "gravy", "resin", "inlet", "lager", "reset", "dries"  ],
							[ "capacious", "unusually", "septuplet", "teensiest",
							  "aloft", "award", "igloo", "undue", "exude", "treat", "ripup", "moose",
							  "ebola", "noted", "laden", "ovens", "inert", "souse", "rumba", "prowl"  ],
							[ "nephritic", "collapsed", "damnedest", "wishfully",
							  "event", "hatch", "idiot", "islet", "terra", "learn", "beard", "idols",
							  "inert", "hitch", "igloo", "total", "until", "larva", "blimp", "alone"  ],
							[ "tenements", "urologist", "mesmerise", "valueless",
							  "event", "easel", "elves", "tithe", "canoe", "strum", "amour", "ovals",
							  "abets", "until", "voter", "steel", "locus", "saner", "among", "opals"  ],		//350
							[ "intuition", "seventies", "raindrops", "eliciting",
							  "nerve", "usher", "tramp", "ombre", "tibia", "sheen", "rebar", "stamp",
							  "larch", "cheer", "amble", "piece", "totes", "noble", "reset", "brace"  ],
							[ "kinkiness", "handsewed", "leniently", "kerchiefs",
							  "issue", "kayak", "noter", "scalp", "elude", "swami", "addon", "skull",
							  "essay", "creak", "tiara", "rapid", "ideas", "fauna", "aisle", "douse"  ],
							[ "licensing", "orderlies", "migration", "snickered",
							  "inner", "evade", "sheet", "nerve", "chili", "later", "craft", "radio",
							  "ninja", "curse", "error", "theme", "excel", "edict", "carol", "addle"  ],
							[ "fulminate", "verbosely", "recruiter", "hereafter",
							  "utter", "murky", "never", "torch", "abate", "loser", "ennui", "haste",
							  "enter", "early", "verge", "rehab", "flail", "exams", "ethos", "nasal"  ],
							[ "colleague", "mentalist", "elbowroom", "drumstick",
							  "ogres", "lunar", "aroma", "usage", "novel", "tango", "motor", "disco",
							  "rerun", "miser", "ovate", "avert", "tenet", "coven", "model", "tests"  ],
							[ "suntanned", "telemetry", "landmines", "apparatus",
							  "usurp", "tibia", "noter", "elide", "delta", "rated", "swami", "grove",
							  "plumb", "alpha", "twine", "reeve", "adder", "unlit", "segue", "amour"  ],
							[ "parakeets", "youngster", "skyrocket", "reopening",
							  "addle", "agree", "erred", "tatty", "track", "laser", "logic", "shame",
							  "elder", "piece", "ratio", "doyen", "natal", "nears", "loses", "grace"  ],
							[ "imploring", "potsherds", "insolence", "alienated",
							  "moats", "loyal", "rodeo", "noter", "deign", "ditto", "lithe", "cynic",
							  "leafy", "easel", "ditto", "ogres", "aided", "edict", "lucre", "toned"  ],
							[ "cofounded", "graduates", "blameless", "successor",
							  "onset", "outer", "noses", "eerie", "natal", "carom", "atoll", "obeys",
							  "upset", "cater", "sorer", "sherd", "sonic", "otter", "aroma", "obese"  ],
							[ "throttled", "bedspread", "instigate", "hairbrush",
							  "hello", "onset", "twerp", "ebola", "drawn", "spent", "among", "greet",
							  "atlas", "roost", "emote", "peaks", "rides", "slate", "anger", "opera"  ],		//360
							[ "parakeets", "defenders", "undersoil", "pampering",
							  "attic", "aided", "expel", "three", "canon", "stage", "poses", "khaki",
							  "acted", "paced", "puree", "liege", "rocks", "ninja", "poked", "stair"  ],
							[ "glorifies", "unfolding", "cosmetics", "conducted",
							  "lying", "remit", "fight", "elven", "ditto", "swarm", "bleat", "aztec",
							  "opium", "digit", "given", "tango", "codes", "extra", "bland", "eaten"  ],
							[ "polygraph", "headaches", "accretion", "opponents",
							  "ounce", "yacht", "radio", "pearl", "sonic", "enter", "inlet", "nitro",
							  "panic", "overt", "drape", "ogled", "ensue", "tenet", "ionic", "lithe"  ],
							[ "syllogism", "yachtsmen", "lambasted", "libations",
							  "yanks", "lucre", "gavel", "storm", "circa", "rehab", "nests", "pence",
							  "ionic", "aisle", "viola", "lymph", "incur", "north", "napes", "sense"  ],
							[ "radically", "heartland", "inability", "eastbound",
							  "abbot", "inter", "apace", "leper", "elven", "throb", "vowel", "civet",
							  "ambit", "tutor", "ample", "error", "overt", "never", "vocal", "woven"  ],
							[ "vocations", "cassettes", "waywardly", "rectified",
							  "olden", "audit", "inert", "nooks", "extra", "straw", "alter", "spill",
							  "ended", "tenet", "ebola", "tests", "feels", "enter", "asset", "trite"  ],
							[ "rainproof", "telepathy", "discharge", "fallacies",
							  "amass", "names", "regal", "orate", "alibi", "music", "tibia", "among",
							  "alarm", "loses", "grade", "liege", "claim", "exits", "tiara", "broth"  ],
							[ "sleepover", "eminences", "bandwidth", "renovated",
							  "lunch", "elide", "oasis", "erode", "hydra", "roped", "sushi", "alert",
							  "ennui", "ochre", "storm", "sheen", "abhor", "endup", "stain", "suede"  ],
							[ "witticism", "megapixel", "uniformed", "transpire",
							  "ingot", "tally", "clasp", "skier", "organ", "sheaf", "eager", "olive",
							  "regal", "nutty", "alive", "parka", "pious", "rogue", "emoji", "grime"  ],
							[ "schooners", "celebrate", "packaging", "sapsucker",
							  "cause", "obese", "nests", "robin", "mania", "trick", "doing", "clean",
							  "azure", "sieve", "sabre", "since", "comet", "ennui", "decor", "inert"  ],		//370
							[ "formality", "uppermost", "motorcade", "unchanged",
							  "ovals", "musty", "leper", "trice", "metro", "dingo", "magic", "dried",
							  "nears", "husky", "primp", "reeve", "nomad", "eaten", "madam", "grins"  ],
							[ "pectorals", "zookeeper", "fragrance", "terahertz",
							  "embed", "tarot", "rabid", "lance", "donor", "wrong", "media", "panic",
							  "ember", "audit", "bingo", "dreck", "endow", "tango", "maple", "dance"  ],
							[ "austerity", "starboard", "embalming", "upcountry",
							  "union", "timed", "route", "timid", "scram", "larva", "groom", "crown",
							  "prism", "owned", "unmet", "elder", "nasal", "rarer", "gecko", "odour"  ],
							[ "laudatory", "cortisone", "meridians", "magnified",
							  "amber", "ditch", "tract", "rodeo", "imbue", "radii", "sushi", "chain",
							  "ambit", "north", "audio", "trout", "friar", "embed", "sects", "swain"  ],
							[ "ambiguous", "venomless", "profusion", "distorted",
							  "melee", "irons", "upped", "upset", "carer", "shelf", "watts", "outdo",
							  "igloo", "tiers", "paste", "ditto", "rocks", "eerie", "whorl", "totes"  ],
							[ "massacred", "glittered", "newlyweds", "obedience",
							  "aside", "shred", "chant", "elide", "elite", "sigil", "endow", "sound",
							  "briar", "dread", "axial", "theft", "evens", "cling", "ensue", "douse"  ],
							[ "calloused", "redbreast", "hexagonal", "operation",
							  "ahead", "lingo", "udder", "earth", "brace", "omega", "limbo", "china",
							  "preen", "rodeo", "dirge", "rehab", "taboo", "ovate", "lucre", "mails"  ],
							[ "southwest", "feudatory", "spineless", "enhancing",
							  "olive", "treat", "whisk", "stage", "whelp", "rayon", "panel", "locus",
							  "naive", "alert", "image", "knead", "cower", "needy", "pilot", "nicer"  ],
							[ "facepalms", "personnel", "imparting", "egomaniac",
							  "alias", "entry", "argon", "minus", "steam", "drama", "sheet", "logon",
							  "guilt", "messy", "genre", "noses", "nosed", "arena", "salon", "eagle"  ],
							[ "canonical", "organizes", "adoringly", "necessary",
							  "along", "oasis", "inept", "amber", "tread", "dryer", "futon", "nasal",
							  "ebons", "edges", "ember", "terra", "sated", "reedy", "fungi", "taste"  ],		//380
							[ "discovery", "undresses", "sophomore", "unwelcome",
							  "icing", "cheat", "video", "roach", "rodeo", "ditch", "modem", "trier",
							  "noise", "eight", "drawn", "other", "cared", "midst", "mites", "drive"  ],
							[ "dehydrate", "behemoths", "passports", "jointless",
							  "event", "years", "recap", "taboo", "sigma", "reeds", "video", "roust",
							  "opera", "notes", "cable", "prone", "laser", "segue", "virgo", "dough"  ],
							[ "campaigns", "nanometer", "chrysalis", "utterance",
							  "anger", "patch", "itchy", "north", "hutch", "nappy", "aroma", "swami",
							  "tight", "earth", "circa", "yahoo", "ashen", "cutup", "aisle", "orate"  ],
							[ "botanical", "prosecute", "miscreant", "withstood",
							  "offer", "apron", "imply", "aspen", "chili", "tonic", "plate", "nylon",
							  "infer", "heron", "paper", "yanks", "tacit", "onion", "panic", "allot"  ],
							[ "scantiest", "faintness", "cementing", "decorated",
							  "crime", "nests", "input", "slack", "chafe", "delve", "leapt", "doyen",
							  "exits", "ovens", "plaza", "token", "arced", "email", "laden", "abyss"  ],
							[ "ecosphere", "handsewed", "milliwatt", "panellist",
							  "crowd", "sired", "hauls", "robot", "chili", "legal", "sinew", "erect",
							  "amour", "ended", "umbra", "sated", "local", "sling", "scene", "niece"  ],
							[ "sentience", "terminate", "initiated", "emigrants",
							  "enter", "tired", "eject", "clout", "drawn", "posit", "comma", "awake",
							  "meter", "gored", "elope", "totem", "addup", "toads", "chain", "meant"  ],
							[ "heinously", "retreated", "ostriches", "outdazzle",
							  "enter", "niece", "uncut", "lucre", "nicks", "solar", "panic", "noise",
							  "untie", "dirge", "cache", "their", "zings", "local", "panda", "naive"  ],
							[ "outdoorsy", "hydration", "interrupt", "floodgate",
							  "upset", "disco", "obeys", "seize", "union", "tithe", "briar", "setup",
							  "loses", "outdo", "edify", "steer", "grunt", "twist", "beset", "intro"  ],
							[ "furthered", "prosecute", "nocturnal", "toothache",
							  "urges", "tinny", "evict", "enter", "radio", "draft", "tuber", "parka",
							  "organ", "tasty", "inter", "tires", "acrid", "hydra", "topic", "burnt"  ],		//390
							[ "afternoon", "generates", "uncounted", "dedicates",
							  "fluff", "enter", "notch", "opera", "cabin", "torso", "cairn", "place",
							  "erupt", "infer", "these", "heave", "ascot", "ember", "copra", "irate"  ],
							[ "endearing", "uncharted", "validates", "pondering",
							  "nears", "enemy", "react", "nerve", "mocha", "sushi", "tiara", "blaze",
							  "orate", "dusty", "apron", "teeth", "ramps", "nicks", "tuber", "abase"  ],
							[ "bathhouse", "heatsinks", "principle", "naysayers",
							  "angel", "henna", "oasis", "shrug", "goner", "sheen", "sushi", "avail",
							  "argon", "salsa", "spree", "sight", "yogis", "range", "swami", "stalk"  ],
							[ "parodying", "newsbreak", "electrode", "nattering",
							  "abort", "oiled", "young", "niche", "bevel", "lyric", "chair", "wield",
							  "atoll", "toted", "uncle", "guess", "rebel", "never", "cower", "arena"  ],
							[ "convolute", "calendars", "vitiation", "organists",
							  "outed", "verge", "light", "trace", "emoji", "sushi", "carat", "igloo",
							  "rotor", "addle", "guava", "theme", "items", "tools", "cried", "ruler"  ],
							[ "tightened", "teariness", "interrupt", "partition",
							  "irons", "holds", "exact", "emote", "learn", "taste", "aster", "strip",
							  "atoll", "tests", "anode", "their", "tolet", "ovals", "arson", "tyres"  ],
							[ "occultist", "gratitude", "allowance", "repentant",
							  "clang", "utter", "taste", "swore", "prowl", "credo", "quota", "attic",
							  "exalt", "eager", "scour", "event", "topic", "noone", "quart", "opted"  ],
							[ "accolades", "varnishes", "officials", "agitators",
							  "creed", "octal", "audio", "exact", "dwarf", "sushi", "cacti", "avail",
							  "great", "tidal", "drama", "often", "tides", "roads", "class", "crave"  ],
							[ "halitosis", "pertained", "corporeal", "vampirism",
							  "alive", "ingot", "orbit", "image", "credo", "strip", "safer", "samba",
							  "axing", "pleat", "blare", "theft", "rocks", "shear", "sushi", "femme"  ],
							[ "leavening", "olfactory", "repertory", "throwaway",
							  "enact", "vital", "noise", "nitro", "gnome", "niece", "chest", "abhor",
							  "heart", "octal", "intel", "ebola", "argon", "above", "chart", "ether"  ]
];  //400
