
var TurtleSolutions100 = [ [ "agreement", "astern", "paste", "donut", "pared", "eject" ],
									[ "financial", "magnet", "trace", "eatit", "tinge", "edict" ],
									[ "unbeknown", "pocked", "spoke", "ridge", "sober", "erode" ],
									[ "jumpsuits", "classy", "filed", "dryad", "famed", "dried" ],
									[ "deceivers", "riding", "drink", "rigid", "decor", "knead" ],
									[ "clockwise", "tucked", "found", "radon", "floor", "deign" ],
									[ "weekender", "divest", "cling", "ditty", "creed", "giddy" ],
									[ "penurious", "geared", "smelt", "dodge", "synod", "trope" ],
									[ "quarterly", "pitted", "blind", "lodge", "brawl", "dirge" ],
									[ "blundered", "sender", "fiend", "purse", "frump", "dirge" ],		//10
									[ "pressgang", "lessen", "overt", "nanny", "ocean", "toady" ],
									[ "austerity", "heresy", "break", "thyme", "beset", "knife" ],
									[ "memorized", "stared", "deter", "rider", "demur", "razor" ],
									[ "announcer", "resume", "bleed", "seedy", "bonus", "decay" ],
									[ "birthrate", "rushed", "prude", "hedge", "parch", "evade" ],
									[ "hourglass", "fought", "cross", "deter", "could", "stair" ],
									[ "historian", "shroud", "ethic", "elder", "ensue", "crier" ],
									[ "catalysts", "wallow", "graph", "dowse", "gated", "haste" ],
									[ "sharpened", "propel", "scram", "filth", "staff", "munch" ],
									[ "alertness", "pelted", "wheel", "dodge", "wield", "liege" ],		//20
									[ "logarithm", "outrun", "squib", "tinge", "sight", "bathe" ],
									[ "shameless", "surety", "crust", "style", "crass", "theme" ],
									[ "garrulous", "immune", "mimic", "elect", "merge", "croft" ],
									[ "maligning", "groggy", "surge", "tryst", "split", "evict" ],
									[ "abrogated", "judged", "crust", "elder", "curve", "tutor" ],
									[ "anonymity", "buoyed", "count", "yodel", "crony", "twirl" ],
									[ "seatbelts", "ribbed", "quilt", "madly", "qualm", "tally" ],
									[ "biorhythm", "pathos", "shawl", "loser", "shoal", "later" ],
									[ "mailrooms", "search", "spend", "ethos", "spite", "dross" ],
									[ "flickered", "packer", "drawl", "north", "deign", "lurch" ],		//30
									[ "ablutions", "wanted", "slant", "nudge", "salon", "trope" ],
									[ "trackball", "awoken", "cowed", "linen", "crawl", "drawn" ],
									[ "reopening", "cement", "steep", "rotor", "scour", "prior" ],
									[ "grainiest", "kidney", "reign", "maybe", "realm", "niece" ],
									[ "continual", "defile", "spend", "event", "singe", "doubt" ],
									[ "darkening", "potent", "floss", "total", "first", "swill" ],
									[ "agreement", "astern", "paste", "donut", "pared", "eject" ],
									[ "benefited", "waffle", "flare", "leery", "final", "entry" ],
									[ "ointments", "dimmed", "stilt", "yodel", "sandy", "tonal" ],
									[ "attrition", "fetish", "peeve", "ochre", "patio", "elite" ],		//40
									[ "stepchild", "placid", "cello", "sedge", "chess", "olive" ],
									[ "gathering", "phlegm", "ethos", "armed", "extra", "shied" ],
									[ "cellulose", "refuel", "sheep", "relay", "solar", "proxy" ],
									[ "leapfrogs", "coffin", "cooed", "mince", "charm", "drove" ],
									[ "contusion", "clause", "polka", "stern", "pants", "alien" ],
									[ "tormented", "breeze", "torch", "wield", "throw", "hated" ],
									[ "fulminate", "casing", "draft", "angst", "delta", "toast" ],
									[ "stupefied", "intent", "synod", "gutsy", "slung", "deify" ],
									[ "overboard", "barber", "smart", "dirty", "speed", "teary" ],
									[ "countdown", "bistro", "scion", "alone", "sauna", "noose" ],		//50
									[ "adversely", "scurvy", "cocoa", "tryst", "covet", "alert" ],
									[ "seditious", "cutter", "squad", "eerie", "sedge", "drone" ],
									[ "scavenger", "careen", "shave", "rinse", "stair", "eagle" ],
									[ "stimulate", "ensure", "banjo", "piety", "blimp", "ovary" ],
									[ "childcare", "border", "shove", "puree", "skimp", "evade" ],
									[ "glimpsing", "weapon", "breed", "penal", "blimp", "drill" ],
									[ "rearguard", "ringer", "foist", "tarot", "feast", "toast" ],
									[ "truncated", "rancid", "flail", "elder", "fluke", "later" ],
									[ "ebullient", "rolled", "moose", "daddy", "mound", "every" ],
									[ "limbering", "greedy", "fared", "dryly", "famed", "daily" ],		//60
									[ "excoriate", "roared", "trout", "today", "tacit", "teary" ],
									[ "deadliest", "cellar", "guest", "tired", "grant", "trend" ],
									[ "illogical", "frugal", "peril", "pulse", "polyp", "lucre" ],
									[ "paleology", "record", "break", "yodel", "bulky", "knoll" ],
									[ "blameless", "repeat", "greet", "outer", "guano", "their" ],
									[ "observant", "metred", "blend", "laden", "basil", "drawn" ],
									[ "brutality", "oxtail", "mixed", "nylon", "mourn", "deign" ],
									[ "uninjured", "logjam", "grope", "gummy", "going", "early" ],
									[ "kennelled", "excess", "fixer", "risky", "finer", "rally" ],
									[ "rainstorm", "geisha", "sleet", "plate", "skimp", "trope" ],		//70
									[ "footprint", "crappy", "shred", "doyen", "stood", "deign" ],
									[ "classical", "sensed", "smear", "ladle", "shawl", "recce" ],
									[ "straggler", "beagle", "bleep", "enemy", "borne", "palsy" ],
									[ "formulate", "auburn", "blurt", "tonne", "burst", "trace" ],
									[ "gallstone", "measly", "swept", "tryst", "split", "trout" ],
									[ "uninjured", "logjam", "stoke", "limit", "swill", "egret" ],
									[ "birdbrain", "ramble", "toady", "exert", "three", "yeast" ],
									[ "intricate", "brainy", "scrap", "rhyme", "sitar", "peace" ],
									[ "underfoot", "course", "about", "twerp", "audit", "troop" ],
									[ "leeriness", "region", "wheel", "penny", "whelp", "leery" ],		//80
									[ "hairweave", "subway", "crumb", "dryly", "cried", "beady" ],
									[ "criticism", "uppity", "topic", "flyer", "thief", "crier" ],
									[ "volleying", "tavern", "slain", "tonne", "splat", "naive" ],
									[ "delegates", "bought", "broil", "enter", "belie", "later" ],
									[ "leapfrogs", "sinful", "shine", "palsy", "scamp", "ebony" ],
									[ "veritably", "foetal", "spout", "bully", "scrub", "tabby" ],
									[ "panellist", "volley", "scoop", "rhyme", "saner", "pride" ],
									[ "credulous", "occupy", "focal", "dryly", "freed", "loony" ],
									[ "knowingly", "squirt", "pique", "sitar", "pious", "eager" ],
									[ "captivate", "shrift", "abhor", "nutty", "aspen", "ready" ]		//90
];  //90
//									[ "", "", "", "", "", "" ]
