
//---------------------------------------------
//---------- GRIDIRON GAME --------------------
var GridironGame = function () {
   var CalcPad;
   var ScreenRect;
};
GridironGame.prototype = new GenieGame();
GridironGame.prototype.Set = function(intrfc, gTool, cPad, tWriter, rGenerator) {
   GenieGame.prototype.Set.call(this, intrfc, gTool, tWriter, rGenerator);

   this.CalcPad = cPad;
   this.ScreenRect = new GenieRect();
   this.Components = new GridironComponents();
};
GridironGame.prototype.SetComponents = function() {

   this.Components.Set(this.Interface, this.GraphicsTool, this.CalcPad, this.TextWriter, this.Randomizer, this.ScreenRect);
};
GridironGame.prototype.Start = function() {

	this.DetermineIndices();
   if (Game.CheckPhone()) {
		IntroView.Open();
		IntroView.Update();
	} else
		Intro.Start();
};
GridironGame.prototype.DetermineIndices = function() {
	//UNLOGGED - should be REDUNDANT
	var date, ms;

//	FeaturedIndex = (probably hard-coded)
/*
	date = new Date();
	ms = date.getTime();
	DailyIndex = Math.floor((ms-Milliseconds)/(24*60*60*1000));
	WeeklyIndex = Math.floor((ms-Milliseconds)/(7*24*60*60*1000));
*/
};
GridironGame.prototype.SetPhone = function() {  //UNLOGGED
	GenieGame.prototype.SetPhone.call(this);

	//Gridder view
	VIEW.GRIDDER.L = 0;
	VIEW.GRIDDER.BUTTON.DEMOTE.L -= 90;
	VIEW.GRIDDER.BUTTON.CUT.L -= 90;
	VIEW.GRIDDER.BUTTON.MARK.L = 14;
	VIEW.GRIDDER.BUTTON.UnMARK.L = 89;

	//Retirement view
	VIEW.RETIREMENT.L = 50;
	VIEW.RETIREMENT.T = 50;
	VIEW.RETIREMENT.W = 300;
	VIEW.RETIREMENT.H = 300;
	VIEW.RETIREMENT.BUTTON.OK.L = 180;
	VIEW.RETIREMENT.BUTTON.OK.T = 310;

	//Pending free agent view
	VIEW.TEAmFAs.L = 50;
	VIEW.TEAmFAs.T = 50;
	VIEW.TEAmFAs.W = 300;
	VIEW.TEAmFAs.H = 300;
	VIEW.TEAmFAs.BUTTON.OK.L = 180;
	VIEW.TEAmFAs.BUTTON.OK.T = 310;

	//Draft view
	VIEW.DRAFT.CONSOLE.BUTTON.PREVIEW.L = 38;
	VIEW.DRAFT.CONSOLE.BUTTON.PREVIEW.T = 15;
	VIEW.DRAFT.CONSOLE.BUTTON.PREVIEW.H = 60;
	VIEW.DRAFT.CONSOLE.BUTTON.PREVIEW.SY = 257;
	VIEW.DRAFT.CONSOLE.BUTTON.NEEDS.L = 38;
	VIEW.DRAFT.CONSOLE.BUTTON.NEEDS.T = 90;
	VIEW.DRAFT.CONSOLE.BUTTON.NEEDS.H = 60;
	VIEW.DRAFT.CONSOLE.BUTTON.NEEDS.SY = 61;
	VIEW.DRAFT.CONSOLE.BUTTON.START.L = 38;
	VIEW.DRAFT.CONSOLE.BUTTON.START.T = 165;
	VIEW.DRAFT.CONSOLE.BUTTON.START.H = 60;
	VIEW.DRAFT.CONSOLE.BUTTON.START.SY = 353;
	VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.L = VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.MOBILE.L;
	VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.T = VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.MOBILE.T;
	VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.H = VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.MOBILE.H;
	VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.SX = VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.MOBILE.SX;
	VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.SY = VIEW.DRAFT.CONSOLE.BUTTON.PROJECTS.MOBILE.SY;
	VIEW.DRAFT.CONSOLE.BUTTON.CAMP.L = VIEW.DRAFT.CONSOLE.BUTTON.CAMP.MOBILE.L;
	VIEW.DRAFT.CONSOLE.BUTTON.CAMP.T = VIEW.DRAFT.CONSOLE.BUTTON.CAMP.MOBILE.T;
	VIEW.DRAFT.CONSOLE.BUTTON.CAMP.H = VIEW.DRAFT.CONSOLE.BUTTON.CAMP.MOBILE.H;
	VIEW.DRAFT.CONSOLE.BUTTON.CAMP.SX = VIEW.DRAFT.CONSOLE.BUTTON.CAMP.MOBILE.SX;
	VIEW.DRAFT.CONSOLE.BUTTON.CAMP.SY = VIEW.DRAFT.CONSOLE.BUTTON.CAMP.MOBILE.SY;

	//Trade down view
	VIEW.DRAFT.TRADeDOWN.L = VIEW.DRAFT.TRADeDOWN.MOBILE.L;
	VIEW.DRAFT.TRADeDOWN.T = VIEW.DRAFT.TRADeDOWN.MOBILE.T;
	VIEW.DRAFT.TRADeDOWN.BUTTON.CANCEL.L = VIEW.DRAFT.TRADeDOWN.BUTTON.CANCEL.MOBILE.L;
	VIEW.DRAFT.TRADeDOWN.BUTTON.CANCEL.T = VIEW.DRAFT.TRADeDOWN.BUTTON.CANCEL.MOBILE.T;
	VIEW.DRAFT.TRADeDOWN.BUTTON.OK.L = VIEW.DRAFT.TRADeDOWN.BUTTON.OK.MOBILE.L;
	VIEW.DRAFT.TRADeDOWN.BUTTON.OK.T = VIEW.DRAFT.TRADeDOWN.BUTTON.OK.MOBILE.T;

	this.SetPhoneProjectsView();
	this.SetPhoneCampView();
	this.SetSeasonView();
};
GridironGame.prototype.SetPhoneProjectsView = function() {

	//Dimensions
	VIEW.DRAFT.PROJECTS.L = VIEW.DRAFT.PROJECTS.MOBILE.L;
	VIEW.DRAFT.PROJECTS.T = VIEW.DRAFT.PROJECTS.MOBILE.T;

	//Controls
	VIEW.DRAFT.PROJECTS.BUTTON.YES.L = VIEW.DRAFT.PROJECTS.BUTTON.YES.MOBILE.L;
	VIEW.DRAFT.PROJECTS.BUTTON.YES.T = VIEW.DRAFT.PROJECTS.BUTTON.YES.MOBILE.T;
	VIEW.DRAFT.PROJECTS.BUTTON.NO.L = VIEW.DRAFT.PROJECTS.BUTTON.NO.MOBILE.L;
	VIEW.DRAFT.PROJECTS.BUTTON.NO.T = VIEW.DRAFT.PROJECTS.BUTTON.NO.MOBILE.T;
	VIEW.DRAFT.PROJECTS.BUTTON.OK.L = VIEW.DRAFT.PROJECTS.BUTTON.OK.MOBILE.L;	
	VIEW.DRAFT.PROJECTS.BUTTON.OK.T = VIEW.DRAFT.PROJECTS.BUTTON.OK.MOBILE.T;	
};
GridironGame.prototype.SetPhoneCampView = function() {

	//Dimensions
	VIEW.DRAFT.CAMP.L = VIEW.DRAFT.CAMP.MOBILE.L;
	VIEW.DRAFT.CAMP.T = VIEW.DRAFT.CAMP.MOBILE.T;

	//Images
	VIEW.DRAFT.CAMP.IMAGE.OUTCOME.X = VIEW.DRAFT.CAMP.IMAGE.OUTCOME.MOBILE.X;
	VIEW.DRAFT.CAMP.IMAGE.OUTCOME.Y = VIEW.DRAFT.CAMP.IMAGE.OUTCOME.MOBILE.Y;

	//Controls
	VIEW.DRAFT.CAMP.BUTTON.CAUTIOUS.L = VIEW.DRAFT.CAMP.BUTTON.CAUTIOUS.MOBILE.L;
	VIEW.DRAFT.CAMP.BUTTON.CAUTIOUS.T = VIEW.DRAFT.CAMP.BUTTON.CAUTIOUS.MOBILE.T;
	VIEW.DRAFT.CAMP.BUTTON.BALANCED.L = VIEW.DRAFT.CAMP.BUTTON.BALANCED.MOBILE.L;
	VIEW.DRAFT.CAMP.BUTTON.BALANCED.T = VIEW.DRAFT.CAMP.BUTTON.BALANCED.MOBILE.T;
	VIEW.DRAFT.CAMP.BUTTON.INTENSE.L = VIEW.DRAFT.CAMP.BUTTON.INTENSE.MOBILE.L;	
	VIEW.DRAFT.CAMP.BUTTON.INTENSE.T = VIEW.DRAFT.CAMP.BUTTON.INTENSE.MOBILE.T;	
	VIEW.DRAFT.CAMP.BUTTON.OK.L = VIEW.DRAFT.CAMP.BUTTON.OK.MOBILE.L;	
	VIEW.DRAFT.CAMP.BUTTON.OK.T = VIEW.DRAFT.CAMP.BUTTON.OK.MOBILE.T;	
};
GridironGame.prototype.SetSeasonView = function() {

	VIEW.MATChUPs.L = VIEW.MATChUPs.MOBILE.L;
	VIEW.MATChUPs.T = VIEW.MATChUPs.MOBILE.T;

	VIEW.MATCH.STATS.L = VIEW.MATCH.STATS.MOBILE.L;
	VIEW.MATCH.STATS.T = VIEW.MATCH.STATS.MOBILE.T;
	VIEW.MATCH.STATS.BUTTON.OK.L = VIEW.MATCH.STATS.BUTTON.OK.MOBILE.L;	
	VIEW.MATCH.STATS.BUTTON.OK.T = VIEW.MATCH.STATS.BUTTON.OK.MOBILE.T;	
};
