//+1
var SpindleWords = [ "knickknacks", "nonchalance", "fabrication", "acclamation", "cohabitates", "singularity", "concurrence", "calligraphy",
							"termination", "persnickety", "reconnoitre", "demarcation", "beleaguered", "chronometer", "magnificent", "beneficiary",
							"abomination", "reminiscent", "caffeinated", "anticipated", "incinerated", "edification", "magnanimous", "combustible",
							"camaraderie", "peripatetic", "obfuscation", "palindromes", "maintenance", "hairstylist", "punctuality", "intelligent",
							"fabrication", "ignominious", "coruscating", "kleptomania", "kindhearted", "backstabbed", "calculating", "calibration",
							"perpetrator", "singularity", "fantabulous", "fairgrounds", "abnormality", "participant", "egalitarian", "femmefatale",
							"mountaineer", "acrimonious", "gastronomic", "reprimanded", "narcoleptic", "ideological", "dilapidated", "cacophonous",
							"machination", "callousness", "spokesmodel", "paperweight", "entertainer", "immigration", "landscaping", "needlepoint",
							"beleaguered", "information", "appropriate", "traditional", "responsible", "substantial", "opportunity", "eradication",
							"comfortable", "immediately", "complicated", "cornerstone", "highlighter", "cataclysmic", "rainforests", "fascination",		//80
							"independent", "abracadabra", "rapscallion", "battlefield", "declaration", "sacramental", "egotistical", "serendipity",
							"generations", "candlelight", "electricity", "inscription", "hallucinate", "geopolitics", "electronics", "safecracker",
							"candlestick", "insouciance", "mathematics", "handwriting", "geometrical", "scrumptious", "legislation", "deferential",
							"constipated", "handcrafted", "oncloudnine", "recognition", "reciprocate", "neurologist", "illustrated", "enchantress",
							"imagination", "felicitated", "sarcophagus", "counterpart", "embroidered", "synchronize", "criminology", "standoffish",
							"housekeeper", "bullfighter", "misanthrope", "compression", "amalgamated", "infiltrator", "malapropism", "dissolution",
							"skeletonkey", "ingredients", "titillation", "dissociated", "centripetal", "implication", "suppressant", "concentrate",
							"loudmouthed", "nondescript", "fluorescent", "regrettable", "billionaire", "frustration", "stockbroker", "connoisseur",
							"gesticulate", "tracheotomy", "subcontract", "designation", "renaissance", "contentment", "streamlined", "cylindrical",
							"information", "draughtsman", "breadwinner", "aerodynamic", "masculinity", "emancipated", "lightweight", "bibliophile",		//160
							"speedometer", "outmaneuver", "whereabouts", "godforsaken", "tonsillitis", "metaphysics", "trustworthy", "disembodied",
							"stipulation", "considerate", "inheritance", "planetarium", "impeachment", "humiliation", "scaffolding", "dreadnought",
							"superiority", "intentional", "sleepwalked", "demonstrate", "transparent", "dislocation", "preparation", "apocalyptic",
							"collectable", "nightingale", "industrious", "supermarket", "compartment", "indignation", "regurgitate", "affectation",
							"persistence", "commodities", "perceptible", "assimilated", "impersonate", "speculation", "atmospheric", "fundamental",
							"appointment", "measurement", "abstraction", "demographic", "pterodactyl", "optometrist", "floodlights", "segregation",
							"confederacy", "trendsetter", "commiserate", "aristocracy", "lubrication", "transponder", "gingerbread", "replacement",
							"contraption", "association", "moisturizer", "brainwashed", "presumption", "constituent", "consecrated", "trailblazer",
							"unbreakable", "incremental", "thermometer", "cartography", "incongruous", "submersible", "enunciation", "oscillating",
							"disembarked", "unconscious", "dumbfounded", "resourceful", "catchphrase", "ghostwriter", "retaliation", "disseminate",		//240
							"untouchable", "documentary", "collaborate", "indigestion", "insecticide", "incarnation", "dermatology", "microscopic",
							"photography", "archipelago", "fragmentary", "subordinate", "butterflies", "restriction", "interpreter", "illusionist",
							"infomercial", "thickheaded", "diagnostics", "spontaneous", "adolescence", "furthermore", "predisposed", "hydrocarbon",
							"correlation", "freemasonry", "grasshopper", "sweepstakes", "contributor", "orthoscopic", "endorsement", "prohibition",
							"conspicuous", "resplendent", "refurbished", "antibiotics", "integration", "displeasure", "predicament", "belligerent",
							"megalomania", "remonstrate", "destruction", "mathematics", "bulletproof", "hibernation", "unblemished", "enchantment",
							"theoretical", "compunction", "libertarian", "scattershot", "crestfallen", "progression", "opportunity", "complacency",
							"grandmother", "supposition", "embellished", "transmitter", "denunciated", "perforation", "discrepancy", "wintergreen",
							"torchbearer", "composition", "impertinent", "renumerated", "leapfrogged", "flirtatious", "nourishment", "citizenship",
							"repetitious", "charismatic", "intractable", "omniscience", "cosmetology", "prepackaged", "comportment", "persecution",		//320
							"sensational", "cheerleader", "implausible", "afficionado", "indifferent", "uninhibited", "remorseless", "authorities",
							"mollycoddle", "utilitarian", "corporation", "marginalize", "sympathetic", "computation", "loudspeaker", "suspenseful",
							"condolences", "personalize", "recuperated", "firefighter", "respectable", "collectible", "mesmerising", "unvarnished",
							"snakebitten", "placeholder", "cliffhanger", "insinuation", "woodchipper", "ditchdigger", "reenactment", "stakeholder",
							"consolation", "meritocracy", "shortcoming", "osteopathic", "arbitration", "instruction", "resignation", "unfortunate",
							"smithereens", "luminescent", "illuminated", "infatuation", "contaminant", "concordance", "marshmallow", "strategized",
							"cockroaches", "insincerity", "searchlight", "chambermaid", "incinerator", "reincarnate", "tamperproof", "condominium",
							"unsolicited", "directorate", "merchandise", "thoughtless", "clandestine", "bombardment", "distraction", "transporter",
							"infantryman", "titillating", "coefficient", "inspiration", "storyteller", "disgraceful", "premonition", "technophile",
							"stimulating", "enhancement", "spendthrift", "distasteful", "orchestrate", "distinguish", "personality", "tattletales",		//400
							"altercation", "percentages", "unspecified", "cybernetics", "microcredit", "thunderbolt", "discography", "malfeasance",
							"stagestruck", "refrigerate", "celebration", "institution", "peacekeeper", "meaningless", "toastmaster", "copyrighted",
							"incarcerate", "rudimentary", "prehistoric", "electrician", "crowdfunded", "outdoorsman", "dereliction", "influential",
							"wherewithal", "centrifugal", "impractical", "theological", "impregnable", "sublimation", "application", "permutation",
							"archaeology", "meteorology", "perfunctory", "disobedient", "poltergeist", "bureaucracy", "proliferate", "commandment",
							"scholarship", "disoriented", "minesweeper", "troublesome", "colonialism", "matriculate", "unflappable", "coincidence",
							"subsistence", "incontinent", "wheelbarrow", "consistency", "intermingle", "uninitiated", "indomitable", "touchscreen",
							"pollination", "wrongheaded", "liposuction", "syndication", "caterpillar", "flamboyance", "pretentious", "credentials",
							"transfusion", "cauliflower", "iridescence", "sustainable", "conurbation", "melancholic", "ambiguities", "rectangular",
							"uncertainty", "comeuppance", "mantelpiece", "chairperson", "intolerable", "nonsensical", "sentimental", "brotherhood",		//480
							"arrangement", "misinformed", "inopportune", "motorsports", "unrepentant", "crematorium", "mockingbird", "punctuation",
							"marketplace", "malpractice", "haemoglobin", "inefficient", "mountaintop", "foreclosure", "formalities", "infatuation",
							"trepidation", "incorporate", "chamberlain", "sugarcoated", "contemplate", "predestined", "contingency", "millionaire",
							"blockbuster", "proceedings", "telecommute", "infestation", "triangulate", "dysfunction", "physicality", "preferences",
							"matrimonial", "inferiority", "promulgated", "distinction", "reclamation", "consignment", "consumption", "millisecond",
							"innumerable", "certificate", "combination", "personified", "unbeknownst", "enlightened", "procurement", "instability",
							"compilation", "reciprocate", "communicate", "masterpiece", "triceratops", "detrimental", "psychedelic", "forthcoming",
							"unrealistic", "bittersweet", "incompetent", "proficiency", "disciplined", "certifiable", "seismograph", "established",
							"reliability", "indubitably", "peripatetic", "clothesline", "susceptible", "counterfeit", "proprietary", "problematic",
							"cheesesteak", "prestigious", "discredited", "pressurized", "grandparent", "corroborate", "pessimistic", "malfunction",		//560
							"circulation", "photocopier", "spreadsheet", "catastrophe", "intercessor", "bellybutton", "incredulous", "remembrance",
							"degradation", "proletariat", "respiration", "prosecution", "coordinates", "installment", "stigmatized", "inclination",
							"retribution", "disgruntled", "reciprocity", "rattlesnake", "methodology", "switchblade", "mustachioed", "subtraction",
							"tempestuous", "romanticise", "ineffectual", "countryside", "transaction", "sponsorship", "resemblance", "commonplace",
							"disregarded", "monstrosity", "unification", "coffeemaker", "forbearance", "terminology", "proletarian", "hitchhiking",
							"sociologist", "munificence", "cooperation", "pescatarian", "unwillingly", "instigation", "tribulation", "pontificate",
							"protagonist", "acupuncture", "defenceless", "refreshment", "criminalist", "disposition", "premeditate", "temperature",
							"steamrolled", "unmitigated", "granularity", "unpalatable", "disinfected", "transformer", "sensibility", "scuttlebutt",
							"geomagnetic", "shuttlecock", "treacherous", "moneylender", "stenography", "predominant", "misconstrue", "aphrodisiac",
							"unimportant", "fashionable", "powerbroker", "ameliorated", "restitution", "predecessor", "policewoman", "recruitment",		//640
							"firecracker", "musclebound", "grandfather", "nonetheless", "pericardium", "engineering", "accommodate", "desperation",
							"preliminary", "temperament", "unfulfilled", "significant", "dehydration", "fingerprint", "partnership", "peculiarity",
							"competition", "androgynous", "snowboarder", "performance", "intimidated", "outstanding", "putrescence", "complacency",
							"substandard", "unrelenting", "negotiation", "paratrooper", "anachronism", "duplication", "contentious", "destitution",
							"description", "irrefutable", "predictable", "annihilated", "empowerment", "outnumbered", "subtropical", "coordinated",
							"housebroken", "destination", "grandmaster", "deteriorate", "honeysuckle", "lightheaded", "destabilize", "accumulated",
							"accountable"
];
